-- Description:
-- Package generated by VHDL Producer:

-- ========================================================
-- from VHDL producer:

-- Module ID: 5

-- Name of L1 Trigger Menu:
-- L1Menu_CollisionsHeavyIons2018_v4_2_0

-- Unique ID of L1 Trigger Menu:
-- 18def6b5-725e-4ccd-bd48-aa6c63158cc8

-- Unique ID of firmware implementation:
-- a52f5ad9-78f6-4765-a14c-a24029f177a8

-- Scale set:
-- scales_2018_08_07

-- VHDL producer version
-- v3.0.0
-- ========================================================

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;
use ieee.numeric_std.all;

package l1menu_pkg is

-- content of ugt_constants.vhd generated by VHDL Producer formerly

-- Algorithms
constant NR_ALGOS : positive := 110; -- number of algorithmns (min. 32 for FDL registers width !!!) - written by TME

constant MODULE_ID : integer := 5;
-- -- HB 2014-02-28: changed to UUID generated by TME (128 bits = 4 x 32 bits)
constant L1TM_UID : std_logic_vector(127 downto 0) := X"18def6b5725e4ccdbd48aa6c63158cc8";
-- -- HB 2014-05-21: L1TM_NAME generated by TME (1024 bits = 32 x 32 bits)
-- -- has to be interpreted as 128 ASCII-characters (from right to left)
constant L1TM_NAME : std_logic_vector(128*8-1 downto 0) := X"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000305f325f34765f38313032736e6f497976616548736e6f6973696c6c6f435f756e654d314c";

-- -- Unique fireware instance ID generated by the compiler, provided to keep track of multiple menu implementations.
constant L1TM_FW_UID : std_logic_vector(127 downto 0) := X"a52f5ad978f64765a14ca24029f177a8";
--
-- -- Trigger Menu Editor software version - written by TME
constant L1TM_COMPILER_MAJOR_VERSION      : integer range 0 to 255 := 3;
constant L1TM_COMPILER_MINOR_VERSION      : integer range 0 to 255 := 0;
constant L1TM_COMPILER_REV_VERSION        : integer range 0 to 255 := 0;
constant L1TM_COMPILER_VERSION : std_logic_vector(31 downto 0) := X"00" &
           std_logic_vector(to_unsigned(L1TM_COMPILER_MAJOR_VERSION, 8)) &
           std_logic_vector(to_unsigned(L1TM_COMPILER_MINOR_VERSION, 8)) &
           std_logic_vector(to_unsigned(L1TM_COMPILER_REV_VERSION, 8));

constant SVN_REVISION_NUMBER : std_logic_vector(31 downto 0) := X"00000000";
constant L1TM_UID_HASH : std_logic_vector(31 downto 0) := X"13D23CD7";
constant FW_UID_HASH : std_logic_vector(31 downto 0) := X"9B2AC505";

-- content of algo_index.vhd generated by VHDL Producer formerly

-- HB 2016-09-16: constants for algo_mapping_rop.
type global_index_array is array (0 to NR_ALGOS-1) of integer;
constant global_index: global_index_array := (
        393, -- module_index: 0, name: L1_SingleEG15_SingleJet44_MidEta2p7_MinDr0p4_BptxAND
        381, -- module_index: 1, name: L1_SingleEG7_SingleJet60_MidEta2p7_MinDr0p4_BptxAND
        246, -- module_index: 2, name: L1_DoubleMu0_NotMinimumBiasHF2_AND_BptxAND
        460, -- module_index: 3, name: L1_ETT50_ETTAsym60_NotMinimumBiasHF2_OR_BptxAND
        361, -- module_index: 4, name: L1_SingleEG5_NotMinimumBiasHF2_AND_BptxAND
        455, -- module_index: 5, name: L1_ETT50_ETTAsym65_MinimumBiasHF2_OR_BptxAND
        165, -- module_index: 6, name: L1_MinimumBiasHF2_OR_BptxAND
        359, -- module_index: 7, name: L1_SingleEG5_NotMinimumBiasHF2_OR_BptxAND
        456, -- module_index: 8, name: L1_ETT50_ETTAsym70_MinimumBiasHF2_OR_BptxAND
        483, -- module_index: 9, name: L1_NotETT95_MinimumBiasHF2_OR_BptxAND
        426, -- module_index: 10, name: L1_ETTAsym60_NotMinimumBiasHF2_OR_BptxAND
        467, -- module_index: 11, name: L1_ETT65_ETTAsym80_MinimumBiasHF2_OR_BptxAND
        461, -- module_index: 12, name: L1_ETT50_ETTAsym70_NotMinimumBiasHF2_OR_BptxAND
        245, -- module_index: 13, name: L1_DoubleMu0_NotMinimumBiasHF2_OR_BptxAND
        457, -- module_index: 14, name: L1_ETT50_ETTAsym80_MinimumBiasHF2_OR_BptxAND
        462, -- module_index: 15, name: L1_ETT50_ETTAsym80_NotMinimumBiasHF2_OR_BptxAND
        202, -- module_index: 16, name: L1_SingleMuOpen_NotMinimumBiasHF2_AND_BptxAND
        492, -- module_index: 17, name: L1_NotETT110_MinimumBiasHF2_OR_BptxAND
        244, -- module_index: 18, name: L1_DoubleMuOpen_NotMinimumBiasHF2_OR_BptxAND
        199, -- module_index: 19, name: L1_SingleMuOpen_NotMinimumBiasHF2_OR_BptxAND
        464, -- module_index: 20, name: L1_ETT60_ETTAsym60_MinimumBiasHF2_OR_BptxAND
        508, -- module_index: 21, name: L1_CastorHighJet_NotMinimumBiasHF2_AND_BptxAND
        427, -- module_index: 22, name: L1_ETTAsym70_NotMinimumBiasHF2_OR_BptxAND
        509, -- module_index: 23, name: L1_CastorHighJet_NotMinimumBiasHF2_OR_BptxAND
        494, -- module_index: 24, name: L1_NotETT150_MinimumBiasHF2_OR_BptxAND
        437, -- module_index: 25, name: L1_ETT5_ETTAsym50_BptxAND
        104, -- module_index: 26, name: L1_ZDC_AND_OR_MinimumBiasHF2_AND_BptxAND
        511, -- module_index: 27, name: L1_CastorHighJet_OR_MinimumBiasHF2_AND_BptxAND
        203, -- module_index: 28, name: L1_SingleMu0_NotMinimumBiasHF2_AND_BptxAND
        105, -- module_index: 29, name: L1_ZDC_AND_OR_MinimumBiasHF2_OR_BptxAND
        201, -- module_index: 30, name: L1_SingleMu3_NotMinimumBiasHF2_OR_BptxAND
        402, -- module_index: 31, name: L1_DoubleEG2_NotMinimumBiasHF2_AND_BptxAND
        200, -- module_index: 32, name: L1_SingleMu0_NotMinimumBiasHF2_OR_BptxAND
        428, -- module_index: 33, name: L1_ETTAsym80_NotMinimumBiasHF2_OR_BptxAND
        434, -- module_index: 34, name: L1_ETT5_NotMinimumBiasHF2_OR
        400, -- module_index: 35, name: L1_DoubleEG2_NotMinimumBiasHF2_OR_BptxAND
        441, -- module_index: 36, name: L1_ETT5_ETTAsym50_NotMinimumBiasHF2_OR_BptxAND
        451, -- module_index: 37, name: L1_ETT50_ETTAsym40_MinimumBiasHF2_OR_BptxAND
        101, -- module_index: 38, name: L1_ZDC_OR_OR_MinimumBiasHF2_OR_BptxAND
        166, -- module_index: 39, name: L1_NotMinimumBiasHF2_AND
        360, -- module_index: 40, name: L1_SingleEG3_NotMinimumBiasHF2_AND_BptxAND
        481, -- module_index: 41, name: L1_NotETT20_MinimumBiasHF2_OR_BptxAND
        424, -- module_index: 42, name: L1_ETTAsym40_NotMinimumBiasHF2_OR_BptxAND
        167, -- module_index: 43, name: L1_NotMinimumBiasHF2_AND_BptxAND
        458, -- module_index: 44, name: L1_ETT50_ETTAsym40_NotMinimumBiasHF2_OR_BptxAND
        162, -- module_index: 45, name: L1_MinimumBiasHF2_AND
        358, -- module_index: 46, name: L1_SingleEG3_NotMinimumBiasHF2_OR_BptxAND
        452, -- module_index: 47, name: L1_ETT50_ETTAsym50_MinimumBiasHF2_OR_BptxAND
        500, -- module_index: 48, name: L1_CastorMediumJet_NotMinimumBiasHF2_AND_BptxAND
        403, -- module_index: 49, name: L1_DoubleEG5_NotMinimumBiasHF2_AND_BptxAND
        169, -- module_index: 50, name: L1_NotMinimumBiasHF2_OR
        164, -- module_index: 51, name: L1_MinimumBiasHF2_AND_BptxAND
        454, -- module_index: 52, name: L1_ETT50_ETTAsym60_MinimumBiasHF2_OR_BptxAND
        499, -- module_index: 53, name: L1_CastorMediumJet_NotMinimumBiasHF2_OR_BptxAND
        401, -- module_index: 54, name: L1_DoubleEG5_NotMinimumBiasHF2_OR_BptxAND
        459, -- module_index: 55, name: L1_ETT50_ETTAsym50_NotMinimumBiasHF2_OR_BptxAND
        170, -- module_index: 56, name: L1_NotMinimumBiasHF2_OR_BptxAND
        466, -- module_index: 57, name: L1_ETT65_ETTAsym70_MinimumBiasHF2_OR_BptxAND
        482, -- module_index: 58, name: L1_NotETT80_MinimumBiasHF2_OR_BptxAND
        453, -- module_index: 59, name: L1_ETT50_ETTAsym55_MinimumBiasHF2_OR_BptxAND
         27, -- module_index: 60, name: L1_DoubleMuOpen_NotMinimumBiasHF2_AND_BptxAND
        163, -- module_index: 61, name: L1_MinimumBiasHF2_OR
        465, -- module_index: 62, name: L1_ETT60_ETTAsym65_MinimumBiasHF2_OR_BptxAND
        425, -- module_index: 63, name: L1_ETTAsym50_NotMinimumBiasHF2_OR_BptxAND
         29, -- module_index: 64, name: L1_DoubleMu0
         30, -- module_index: 65, name: L1_DoubleMu0_SQ
        236, -- module_index: 66, name: L1_DoubleMu10_BptxAND
        233, -- module_index: 67, name: L1_DoubleMuOpen_OS_BptxAND
        228, -- module_index: 68, name: L1_SingleMu12_SingleEG7_BptxAND
        376, -- module_index: 69, name: L1_SingleEG7_SingleJet32_MidEta2p7_BptxAND
        377, -- module_index: 70, name: L1_SingleEG7_SingleJet40_MidEta2p7_BptxAND
        184, -- module_index: 71, name: L1_SingleMu7_BptxAND
        185, -- module_index: 72, name: L1_SingleMu12_BptxAND
        224, -- module_index: 73, name: L1_SingleMu7_SingleEG7_BptxAND
        346, -- module_index: 74, name: L1_SingleEG7_BptxAND
        208, -- module_index: 75, name: L1_SingleMuOpen_SingleJet28_MidEta2p7_BptxAND
        373, -- module_index: 76, name: L1_SingleEG5_SingleJet28_MidEta2p7_BptxAND
        209, -- module_index: 77, name: L1_SingleMuOpen_SingleJet44_MidEta2p7_BptxAND
        210, -- module_index: 78, name: L1_SingleMuOpen_SingleJet56_MidEta2p7_BptxAND
        345, -- module_index: 79, name: L1_SingleEG5_BptxAND
        211, -- module_index: 80, name: L1_SingleMuOpen_SingleJet64_MidEta2p7_BptxAND
          5, -- module_index: 81, name: L1_SingleMu0_DQ
         15, -- module_index: 82, name: L1_SingleMu12
        186, -- module_index: 83, name: L1_SingleMu16_BptxAND
         23, -- module_index: 84, name: L1_SingleMu22_EMTF
         12, -- module_index: 85, name: L1_SingleMu5
          3, -- module_index: 86, name: L1_SingleMuCosmics_EMTF
         43, -- module_index: 87, name: L1_DoubleEG2
        396, -- module_index: 88, name: L1_DoubleEG2_BptxAND
         44, -- module_index: 89, name: L1_DoubleEG5
        397, -- module_index: 90, name: L1_DoubleEG5_BptxAND
        398, -- module_index: 91, name: L1_DoubleEG8_BptxAND
         65, -- module_index: 92, name: L1_SingleJet120_FWD3p0
        276, -- module_index: 93, name: L1_SingleJet28_FWD_BptxAND
        278, -- module_index: 94, name: L1_SingleJet44_FWD_BptxAND
        274, -- module_index: 95, name: L1_SingleJet8_FWD_BptxAND
         35, -- module_index: 96, name: L1_SingleEG5
         36, -- module_index: 97, name: L1_SingleEG50
        355, -- module_index: 98, name: L1_SingleIsoEG15_BptxAND
        353, -- module_index: 99, name: L1_SingleIsoEG7_BptxAND
        260, -- module_index: 100, name: L1_SingleJet16_BptxAND
        262, -- module_index: 101, name: L1_SingleJet28_BptxAND
        264, -- module_index: 102, name: L1_SingleJet36_BptxAND
        271, -- module_index: 103, name: L1_SingleJet72_BptxAND
        472, -- module_index: 104, name: L1_ETT35_NotETT80_BptxAND
        474, -- module_index: 105, name: L1_ETT45_NotETT110_BptxAND
        476, -- module_index: 106, name: L1_ETT55_NotETT130_BptxAND
         80, -- module_index: 107, name: L1_ETT2000
         70, -- module_index: 108, name: L1_HTT200er
         72, -- module_index: 109, name: L1_HTT360er
    others => 0
);

end package;