-- Description:
-- L1Menu logic generated by VHDL Producer:

-- ========================================================
-- from VHDL producer:

-- Module ID: 2

-- Name of L1 Trigger Menu:
-- L1Menu_test_compare_gtl_struct_v11

-- Unique ID of L1 Trigger Menu:
-- cf20b3d8-7f9f-4e98-ab57-5c2c7a5db555

-- Unique ID of firmware implementation:
-- 2c016b5c-43d6-4090-94f9-db09a5e80811

-- Scale set:
-- scales_2017_05_23

-- VHDL producer version
-- v3.0.0
-- ========================================================

library ieee;
use ieee.std_logic_1164.all;

use work.lhc_data_pkg.all;
use work.gtl_pkg.all;
use work.lut_pkg.all;
use work.l1menu_pkg.all;

entity l1menu is
    port(
        lhc_clk : in std_logic;
        data : in data_pipeline_record;
        conv : in conv_pipeline_record;
        algo : out std_logic_vector(NR_ALGOS-1 downto 0));
end l1menu;

architecture rtl of l1menu is
-- Calculations outputs
    -- Differences
    -- Correlation cuts
    -- Muon charge correlation    
    signal cc_double : obj_bx_muon_cc_double_array;
    signal cc_triple : obj_bx_muon_cc_triple_array;
    signal cc_quad : obj_bx_muon_cc_quad_array;
-- Comparators outputs
    -- Object cuts
    signal comp_pt_jet_bx_m2_0x002e : jet_obj_t;
    signal comp_pt_jet_bx_m2_0x0040 : jet_obj_t;
    signal comp_pt_jet_bx_m2_0x0044 : jet_obj_t;
    signal comp_pt_jet_bx_m2_0x0048 : jet_obj_t;
    signal comp_pt_jet_bx_m1_0x002e : jet_obj_t;
    signal comp_pt_jet_bx_m1_0x0040 : jet_obj_t;
    signal comp_pt_jet_bx_m1_0x0044 : jet_obj_t;
    signal comp_pt_jet_bx_m1_0x0048 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x002e : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0040 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0044 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0048 : jet_obj_t;
    signal comp_pt_jet_bx_p1_0x002e : jet_obj_t;
    signal comp_pt_jet_bx_p1_0x0040 : jet_obj_t;
    signal comp_pt_jet_bx_p1_0x0044 : jet_obj_t;
    signal comp_pt_jet_bx_p1_0x0048 : jet_obj_t;
    signal comp_pt_jet_bx_p2_0x002e : jet_obj_t;
    signal comp_pt_jet_bx_p2_0x0040 : jet_obj_t;
    signal comp_pt_jet_bx_p2_0x0044 : jet_obj_t;
    signal comp_pt_jet_bx_p2_0x0048 : jet_obj_t;
-- Correlation cuts
-- Muon charge correlation
-- Conditions inputs
    -- Object cuts "and"
   signal comb_jet_bx_m2_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_m2_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_m2_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_m2_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_m1_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_m1_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_m1_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_m1_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_p1_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_p1_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_p1_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_p1_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_p2_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_p2_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_p2_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_p2_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
-- Signal definition for conditions names
    signal quad_jet_i2 : std_logic;
    signal quad_jet_i3 : std_logic;
    signal quad_jet_i4 : std_logic;
    signal quad_jet_i5 : std_logic;
    signal quad_jet_i6 : std_logic;
    signal triple_eg_ov_rm_i8 : std_logic;
-- Signal definition for algorithms names
    signal l1_triple_eg_taormdr : std_logic;
    signal l1_quad_jets : std_logic;
begin
-- First stage: calculations
    
-- Second stage: comparisons
    comp_pt_jet_bx_m2_0x002e_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"002E", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(-2)).pt, comp_pt_jet_bx_m2_0x002e
        );
    comp_pt_jet_bx_m2_0x0040_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0040", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(-2)).pt, comp_pt_jet_bx_m2_0x0040
        );
    comp_pt_jet_bx_m2_0x0044_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0044", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(-2)).pt, comp_pt_jet_bx_m2_0x0044
        );
    comp_pt_jet_bx_m2_0x0048_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0048", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(-2)).pt, comp_pt_jet_bx_m2_0x0048
        );
    comp_pt_jet_bx_m1_0x002e_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"002E", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(-1)).pt, comp_pt_jet_bx_m1_0x002e
        );
    comp_pt_jet_bx_m1_0x0040_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0040", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(-1)).pt, comp_pt_jet_bx_m1_0x0040
        );
    comp_pt_jet_bx_m1_0x0044_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0044", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(-1)).pt, comp_pt_jet_bx_m1_0x0044
        );
    comp_pt_jet_bx_m1_0x0048_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0048", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(-1)).pt, comp_pt_jet_bx_m1_0x0048
        );
    comp_pt_jet_bx_0_0x002e_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"002E", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x002e
        );
    comp_pt_jet_bx_0_0x0040_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0040", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0040
        );
    comp_pt_jet_bx_0_0x0044_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0044", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0044
        );
    comp_pt_jet_bx_0_0x0048_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0048", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0048
        );
    comp_pt_jet_bx_p1_0x002e_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"002E", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(1)).pt, comp_pt_jet_bx_p1_0x002e
        );
    comp_pt_jet_bx_p1_0x0040_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0040", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(1)).pt, comp_pt_jet_bx_p1_0x0040
        );
    comp_pt_jet_bx_p1_0x0044_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0044", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(1)).pt, comp_pt_jet_bx_p1_0x0044
        );
    comp_pt_jet_bx_p1_0x0048_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0048", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(1)).pt, comp_pt_jet_bx_p1_0x0048
        );
    comp_pt_jet_bx_p2_0x002e_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"002E", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(2)).pt, comp_pt_jet_bx_p2_0x002e
        );
    comp_pt_jet_bx_p2_0x0040_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0040", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(2)).pt, comp_pt_jet_bx_p2_0x0040
        );
    comp_pt_jet_bx_p2_0x0044_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0044", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(2)).pt, comp_pt_jet_bx_p2_0x0044
        );
    comp_pt_jet_bx_p2_0x0048_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0048", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(2)).pt, comp_pt_jet_bx_p2_0x0048
        );

-- Third stage: conditions and algos
    -- Creating condition inputs (combination of object cuts)
    comb_jet_bx_m2_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_m2_0x002e
    ;

    comb_jet_bx_m2_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_m2_0x0040
    ;

    comb_jet_bx_m2_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_m2_0x0044
    ;

    comb_jet_bx_m2_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_m2_0x0048
    ;

    comb_jet_bx_m1_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_m1_0x002e
    ;

    comb_jet_bx_m1_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_m1_0x0040
    ;

    comb_jet_bx_m1_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_m1_0x0044
    ;

    comb_jet_bx_m1_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_m1_0x0048
    ;

    comb_jet_bx_0_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x002e
    ;

    comb_jet_bx_0_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0040
    ;

    comb_jet_bx_0_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0044
    ;

    comb_jet_bx_0_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0048
    ;

    comb_jet_bx_p1_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_p1_0x002e
    ;

    comb_jet_bx_p1_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_p1_0x0040
    ;

    comb_jet_bx_p1_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_p1_0x0044
    ;

    comb_jet_bx_p1_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_p1_0x0048
    ;

    comb_jet_bx_p2_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_p2_0x002e
    ;

    comb_jet_bx_p2_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_p2_0x0040
    ;

    comb_jet_bx_p2_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_p2_0x0044
    ;

    comb_jet_bx_p2_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_p2_0x0048
    ;

    -- Instantiations of conditions
    cond_quad_jet_i2_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 4,
            ((0,11), (0,11), (0,11), (0,11)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_m2_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_m2_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_m2_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_jet_bx_m2_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => quad_jet_i2
        );
    cond_quad_jet_i3_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 4,
            ((0,11), (0,11), (0,11), (0,11)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_m1_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_m1_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_m1_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_jet_bx_m1_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => quad_jet_i3
        );
    cond_quad_jet_i4_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 4,
            ((0,11), (0,11), (0,11), (0,11)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_0_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_jet_bx_0_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => quad_jet_i4
        );
    cond_quad_jet_i5_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 4,
            ((0,11), (0,11), (0,11), (0,11)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_p1_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_p1_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_p1_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_jet_bx_p1_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => quad_jet_i5
        );
    cond_quad_jet_i6_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 4,
            ((0,11), (0,11), (0,11), (0,11)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_p2_pt_002e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_p2_pt_0040_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_p2_pt_0044_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_jet_bx_p2_pt_0048_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => quad_jet_i6
        );
    cond_triple_eg_ov_rm_i8_i: entity work.combinatorial_conditions_ovrm
        generic map(
            N_EG_OBJECTS, N_TAU_OBJECTS, 3,
            ((0,11), (0,11), (0,11), (0,0)),
            ((0,11), (0,0), (0,0), (0,0))
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_eg_bx_0_pt_0028_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_eg_bx_0_pt_003c_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_eg_bx_0_pt_0050_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_tau_bx_0_pt_003c_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f, 
            dr_ovrm => comp_dr_eg_tau_bx_0_bx_0_0x00000000000000_0x0000000000a028,
            cond_o => triple_eg_ov_rm_i8
        );

    
    -- Centrality assignment
    -- External condition assignment
    -- Instantiations of algorithms

-- 1 L1_triple_eg_taormdr : comb_orm{EG20,EG30,EG40,TAU30}[ORMDR_0p2]
    l1_triple_eg_taormdr <= triple_eg_ov_rm_i8;
    algo(0) <= l1_triple_eg_taormdr;
-- 8 L1_quad_jets : comb{JET23-2,JET32-2,JET34-2,JET36-2} AND comb{JET23-1,JET32-1,JET34-1,JET36-1} AND comb{JET23,JET32,JET34,JET36} AND comb{JET23+1,JET32+1,JET34+1,JET36+1} AND comb{JET23+2,JET32+2,JET34+2,JET36+2}
    l1_quad_jets <= quad_jet_i2 and quad_jet_i3 and quad_jet_i4 and quad_jet_i5 and quad_jet_i6;
    algo(1) <= l1_quad_jets;

end architecture rtl;
