-- Description:
-- L1Menu logic generated by VHDL Producer:

-- ========================================================
-- from VHDL producer:

-- Module ID: 2

-- Name of L1 Trigger Menu:
-- L1Menu_test_esums_instances_v1

-- Unique ID of L1 Trigger Menu:
-- f7b5ee69-e72e-4011-aa54-9fdcb44159a6

-- Unique ID of firmware implementation:
-- 0f60d609-97a3-4ed7-b9ca-23c30a19b2c6

-- Scale set:
-- scales_2017_05_23

-- VHDL producer version
-- v3.1.1
-- ========================================================

library ieee;
use ieee.std_logic_1164.all;

use work.lhc_data_pkg.all;
use work.gtl_pkg.all;
use work.lut_pkg.all;
use work.l1menu_pkg.all;

entity l1menu is
    port(
        lhc_clk : in std_logic;
        data : in data_pipeline_record;
        conv : in conv_pipeline_record;
        algo : out std_logic_vector(NR_ALGOS-1 downto 0));
end l1menu;

architecture rtl of l1menu is
-- Calculations outputs
    -- Differences
    -- Correlation cuts
    -- Muon charge correlation    
    signal cc_double : obj_bx_muon_cc_double_array;
    signal cc_triple : obj_bx_muon_cc_triple_array;
    signal cc_quad : obj_bx_muon_cc_quad_array;
-- Comparators outputs
    -- Object cuts
    signal comp_pt_jet_bx_0_0x0050 : jet_obj_t;
    signal comp_eta_jet_bx_0_0x00c6_0x0039 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0078 : jet_obj_t;
    signal comp_pt_etmhf_bx_0_0x00dc : etmhf_obj_t;
    signal comp_pt_etmhf_bx_0_0x00f0 : etmhf_obj_t;
    signal comp_pt_etmhf_bx_0_0x0104 : etmhf_obj_t;
    signal comp_pt_etmhf_bx_0_0x0064 : etmhf_obj_t;
    signal comp_pt_etmhf_bx_0_0x00b4 : etmhf_obj_t;
    signal comp_pt_etmhf_bx_0_0x0078 : etmhf_obj_t;
    signal comp_pt_etmhf_bx_0_0x00c8 : etmhf_obj_t;
    signal comp_pt_htt_bx_0_0x01e0 : htt_obj_t;
    signal comp_pt_htt_bx_0_0x01f4 : htt_obj_t;
    signal comp_pt_htt_bx_0_0x01b8 : htt_obj_t;
    signal comp_pt_htt_bx_0_0x0078 : htt_obj_t;
    signal comp_pt_htt_bx_0_0x0208 : htt_obj_t;
    signal comp_count_mbt0hfm_bx_0_0x0001 : mbt0hfm_obj_t;
    signal comp_count_mbt0hfp_bx_0_0x0001 : mbt0hfp_obj_t;
    signal comp_pt_mu_bx_0_0x0007 : mu_obj_t;
    signal comp_qual_mu_bx_0_0xf000 : mu_obj_t;
    signal comp_pt_mu_bx_0_0x000d : mu_obj_t;
-- Correlation cuts
-- Muon charge correlation
-- Conditions inputs
    -- Object cuts "and"
   signal comb_jet_bx_0_pt_0050_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0078_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_etmhf_bx_0_pt_00dc_phi_0000_0000_0000_0000 : etmhf_obj_t;
   signal comb_etmhf_bx_0_pt_00f0_phi_0000_0000_0000_0000 : etmhf_obj_t;
   signal comb_etmhf_bx_0_pt_0104_phi_0000_0000_0000_0000 : etmhf_obj_t;
   signal comb_etmhf_bx_0_pt_0064_phi_0000_0000_0000_0000 : etmhf_obj_t;
   signal comb_etmhf_bx_0_pt_00b4_phi_0000_0000_0000_0000 : etmhf_obj_t;
   signal comb_etmhf_bx_0_pt_0078_phi_0000_0000_0000_0000 : etmhf_obj_t;
   signal comb_etmhf_bx_0_pt_00c8_phi_0000_0000_0000_0000 : etmhf_obj_t;
   signal comb_htt_bx_0_pt_01e0_phi_0000_0000_0000_0000 : htt_obj_t;
   signal comb_htt_bx_0_pt_01f4_phi_0000_0000_0000_0000 : htt_obj_t;
   signal comb_htt_bx_0_pt_01b8_phi_0000_0000_0000_0000 : htt_obj_t;
   signal comb_htt_bx_0_pt_0078_phi_0000_0000_0000_0000 : htt_obj_t;
   signal comb_htt_bx_0_pt_0208_phi_0000_0000_0000_0000 : htt_obj_t;
   signal comb_mbt0hfm_bx_0_count_0001 : mbt0hfm_obj_t;
   signal comb_mbt0hfp_bx_0_count_0001 : mbt0hfp_obj_t;
   signal comb_mu_bx_0_pt_0007_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_f000_charge_ign : mu_obj_t;
   signal comb_mu_bx_0_pt_000d_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_f000_charge_ign : mu_obj_t;
-- Signal definition for conditions names
    signal single_ext_i28 : std_logic;
    signal single_ext_i39 : std_logic;
    signal single_ext_i40 : std_logic;
    signal single_ext_i41 : std_logic;
    signal single_ext_i42 : std_logic;
    signal single_mbt0_hfm_i27 : std_logic;
    signal single_mbt0_hfp_i26 : std_logic;
    signal single_etmhf_i10 : std_logic;
    signal single_etmhf_i11 : std_logic;
    signal single_etmhf_i12 : std_logic;
    signal single_etmhf_i20 : std_logic;
    signal single_etmhf_i24 : std_logic;
    signal single_etmhf_i30 : std_logic;
    signal single_etmhf_i9 : std_logic;
    signal single_htt_i17 : std_logic;
    signal single_htt_i18 : std_logic;
    signal single_htt_i23 : std_logic;
    signal single_htt_i25 : std_logic;
    signal single_htt_i31 : std_logic;
    signal double_jet_i22 : std_logic;
    signal double_mu_i19 : std_logic;
    signal single_jet_i21 : std_logic;
    signal single_mu_i16 : std_logic;
-- Signal definition for algorithms names
    signal l1_mu6_htt240er : std_logic;
    signal l1_mu6_htt250er : std_logic;
    signal l1_double_mu3_sq_etmhf50_htt60er : std_logic;
    signal l1_double_mu3_sq_etmhf50_jet60er2p5_or_double_jet40er2p5 : std_logic;
    signal l1_double_mu3_sq_etmhf50_jet60er2p5 : std_logic;
    signal l1_double_mu3_sq_etmhf60_jet60er2p5 : std_logic;
    signal l1_double_mu3_sq_htt220er : std_logic;
    signal l1_double_mu3_sq_htt240er : std_logic;
    signal l1_double_mu3_sq_htt260er : std_logic;
    signal l1_etmhf100 : std_logic;
    signal l1_etmhf110 : std_logic;
    signal l1_etmhf120 : std_logic;
    signal l1_etmhf130 : std_logic;
    signal l1_etmhf90_htt60er : std_logic;
    signal l1_etmhf100_htt60er : std_logic;
    signal l1_etmhf110_htt60er : std_logic;
    signal l1_etmhf120_htt60er : std_logic;
    signal l1_etmhf130_htt60er : std_logic;
    signal l1_etmhf120_not_second_bunch_in_train : std_logic;
    signal l1_etmhf110_htt60er_not_second_bunch_in_train : std_logic;
    signal l1_minimum_bias_hf0_and_bptx_and : std_logic;
begin
-- First stage: calculations
    
-- Second stage: comparisons
    comp_pt_jet_bx_0_0x0050_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0050", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0050
        );
    comp_eta_jet_bx_0_0x00c6_0x0039_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_ETA_WIDTH,
            ETA, X"00C6", X"0039", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).eta, comp_eta_jet_bx_0_0x00c6_0x0039
        );
    comp_pt_jet_bx_0_0x0078_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0078", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0078
        );
    comp_pt_etmhf_bx_0_0x00dc_i: entity work.comparators_obj_cuts
        generic map(
            N_ETMHF_OBJECTS, ETMHF_PT_WIDTH,  
            GE,  
            X"00DC", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.etmhf(bx(0)).pt, comp_pt_etmhf_bx_0_0x00dc
        );
    comp_pt_etmhf_bx_0_0x00f0_i: entity work.comparators_obj_cuts
        generic map(
            N_ETMHF_OBJECTS, ETMHF_PT_WIDTH,  
            GE,  
            X"00F0", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.etmhf(bx(0)).pt, comp_pt_etmhf_bx_0_0x00f0
        );
    comp_pt_etmhf_bx_0_0x0104_i: entity work.comparators_obj_cuts
        generic map(
            N_ETMHF_OBJECTS, ETMHF_PT_WIDTH,  
            GE,  
            X"0104", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.etmhf(bx(0)).pt, comp_pt_etmhf_bx_0_0x0104
        );
    comp_pt_etmhf_bx_0_0x0064_i: entity work.comparators_obj_cuts
        generic map(
            N_ETMHF_OBJECTS, ETMHF_PT_WIDTH,  
            GE,  
            X"0064", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.etmhf(bx(0)).pt, comp_pt_etmhf_bx_0_0x0064
        );
    comp_pt_etmhf_bx_0_0x00b4_i: entity work.comparators_obj_cuts
        generic map(
            N_ETMHF_OBJECTS, ETMHF_PT_WIDTH,  
            GE,  
            X"00B4", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.etmhf(bx(0)).pt, comp_pt_etmhf_bx_0_0x00b4
        );
    comp_pt_etmhf_bx_0_0x0078_i: entity work.comparators_obj_cuts
        generic map(
            N_ETMHF_OBJECTS, ETMHF_PT_WIDTH,  
            GE,  
            X"0078", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.etmhf(bx(0)).pt, comp_pt_etmhf_bx_0_0x0078
        );
    comp_pt_etmhf_bx_0_0x00c8_i: entity work.comparators_obj_cuts
        generic map(
            N_ETMHF_OBJECTS, ETMHF_PT_WIDTH,  
            GE,  
            X"00C8", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.etmhf(bx(0)).pt, comp_pt_etmhf_bx_0_0x00c8
        );
    comp_pt_htt_bx_0_0x01e0_i: entity work.comparators_obj_cuts
        generic map(
            N_HTT_OBJECTS, HTT_PT_WIDTH,  
            GE,  
            X"01E0", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.htt(bx(0)).pt, comp_pt_htt_bx_0_0x01e0
        );
    comp_pt_htt_bx_0_0x01f4_i: entity work.comparators_obj_cuts
        generic map(
            N_HTT_OBJECTS, HTT_PT_WIDTH,  
            GE,  
            X"01F4", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.htt(bx(0)).pt, comp_pt_htt_bx_0_0x01f4
        );
    comp_pt_htt_bx_0_0x01b8_i: entity work.comparators_obj_cuts
        generic map(
            N_HTT_OBJECTS, HTT_PT_WIDTH,  
            GE,  
            X"01B8", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.htt(bx(0)).pt, comp_pt_htt_bx_0_0x01b8
        );
    comp_pt_htt_bx_0_0x0078_i: entity work.comparators_obj_cuts
        generic map(
            N_HTT_OBJECTS, HTT_PT_WIDTH,  
            GE,  
            X"0078", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.htt(bx(0)).pt, comp_pt_htt_bx_0_0x0078
        );
    comp_pt_htt_bx_0_0x0208_i: entity work.comparators_obj_cuts
        generic map(
            N_HTT_OBJECTS, HTT_PT_WIDTH,  
            GE,  
            X"0208", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.htt(bx(0)).pt, comp_pt_htt_bx_0_0x0208
        );
    comp_count_mbt0hfm_bx_0_0x0001_i: entity work.comparators_obj_cuts
        generic map(
            N_MBT0HFM_OBJECTS, MBT0HFM_WIDTH,
            GE, X"0001", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.mbt0hfm(bx(0)).count, comp_count_mbt0hfm_bx_0_0x0001
        );
    comp_count_mbt0hfp_bx_0_0x0001_i: entity work.comparators_obj_cuts
        generic map(
            N_MBT0HFP_OBJECTS, MBT0HFP_WIDTH,
            GE, X"0001", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.mbt0hfp(bx(0)).count, comp_count_mbt0hfp_bx_0_0x0001
        );
    comp_pt_mu_bx_0_0x0007_i: entity work.comparators_obj_cuts
        generic map(
            N_MU_OBJECTS, MU_PT_WIDTH,  
            GE,  
            X"0007", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.mu(bx(0)).pt, comp_pt_mu_bx_0_0x0007
        );
    comp_qual_mu_bx_0_0xf000_i: entity work.comparators_obj_cuts
        generic map(
            N_MU_OBJECTS, MU_QUAL_WIDTH,
            QUAL, X"0000", X"0000", X"F000", "ign"
        )
        port map(
            lhc_clk, data.mu(bx(0)).qual, comp_qual_mu_bx_0_0xf000
        );
    comp_pt_mu_bx_0_0x000d_i: entity work.comparators_obj_cuts
        generic map(
            N_MU_OBJECTS, MU_PT_WIDTH,  
            GE,  
            X"000D", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.mu(bx(0)).pt, comp_pt_mu_bx_0_0x000d
        );

-- Third stage: conditions and algos
    -- Creating condition inputs (combination of object cuts)
    comb_jet_bx_0_pt_0050_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0050
    and 
    (
    comp_eta_jet_bx_0_0x00c6_0x0039
    )
    ;

    comb_jet_bx_0_pt_0078_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0078
    and 
    (
    comp_eta_jet_bx_0_0x00c6_0x0039
    )
    ;

    comb_etmhf_bx_0_pt_00dc_phi_0000_0000_0000_0000 <= 
    comp_pt_etmhf_bx_0_0x00dc
    ;

    comb_etmhf_bx_0_pt_00f0_phi_0000_0000_0000_0000 <= 
    comp_pt_etmhf_bx_0_0x00f0
    ;

    comb_etmhf_bx_0_pt_0104_phi_0000_0000_0000_0000 <= 
    comp_pt_etmhf_bx_0_0x0104
    ;

    comb_etmhf_bx_0_pt_0064_phi_0000_0000_0000_0000 <= 
    comp_pt_etmhf_bx_0_0x0064
    ;

    comb_etmhf_bx_0_pt_00b4_phi_0000_0000_0000_0000 <= 
    comp_pt_etmhf_bx_0_0x00b4
    ;

    comb_etmhf_bx_0_pt_0078_phi_0000_0000_0000_0000 <= 
    comp_pt_etmhf_bx_0_0x0078
    ;

    comb_etmhf_bx_0_pt_00c8_phi_0000_0000_0000_0000 <= 
    comp_pt_etmhf_bx_0_0x00c8
    ;

    comb_htt_bx_0_pt_01e0_phi_0000_0000_0000_0000 <= 
    comp_pt_htt_bx_0_0x01e0
    ;

    comb_htt_bx_0_pt_01f4_phi_0000_0000_0000_0000 <= 
    comp_pt_htt_bx_0_0x01f4
    ;

    comb_htt_bx_0_pt_01b8_phi_0000_0000_0000_0000 <= 
    comp_pt_htt_bx_0_0x01b8
    ;

    comb_htt_bx_0_pt_0078_phi_0000_0000_0000_0000 <= 
    comp_pt_htt_bx_0_0x0078
    ;

    comb_htt_bx_0_pt_0208_phi_0000_0000_0000_0000 <= 
    comp_pt_htt_bx_0_0x0208
    ;

    comb_mbt0hfm_bx_0_count_0001 <= 
    comp_count_mbt0hfm_bx_0_0x0001;

    comb_mbt0hfp_bx_0_count_0001 <= 
    comp_count_mbt0hfp_bx_0_0x0001;

    comb_mu_bx_0_pt_0007_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_f000_charge_ign <= 
    comp_pt_mu_bx_0_0x0007
    and 
    comp_qual_mu_bx_0_0xf000
    ;

    comb_mu_bx_0_pt_000d_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_f000_charge_ign <= 
    comp_pt_mu_bx_0_0x000d
    and 
    comp_qual_mu_bx_0_0xf000
    ;

    -- Instantiations of conditions
    cond_double_jet_i22_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 2,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_0050_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_0050_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => double_jet_i22
        );
    cond_single_jet_i21_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 1,
            ((0,11), (0,0), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_0078_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => single_jet_i21
        );
    cond_single_etmhf_i10_i: entity work.combinatorial_conditions
        generic map(
            N_ETMHF_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_etmhf_bx_0_pt_00dc_phi_0000_0000_0000_0000,
            cond_o => single_etmhf_i10
        );
    cond_single_etmhf_i11_i: entity work.combinatorial_conditions
        generic map(
            N_ETMHF_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_etmhf_bx_0_pt_00f0_phi_0000_0000_0000_0000,
            cond_o => single_etmhf_i11
        );
    cond_single_etmhf_i12_i: entity work.combinatorial_conditions
        generic map(
            N_ETMHF_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_etmhf_bx_0_pt_0104_phi_0000_0000_0000_0000,
            cond_o => single_etmhf_i12
        );
    cond_single_etmhf_i20_i: entity work.combinatorial_conditions
        generic map(
            N_ETMHF_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_etmhf_bx_0_pt_0064_phi_0000_0000_0000_0000,
            cond_o => single_etmhf_i20
        );
    cond_single_etmhf_i24_i: entity work.combinatorial_conditions
        generic map(
            N_ETMHF_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_etmhf_bx_0_pt_00b4_phi_0000_0000_0000_0000,
            cond_o => single_etmhf_i24
        );
    cond_single_etmhf_i30_i: entity work.combinatorial_conditions
        generic map(
            N_ETMHF_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_etmhf_bx_0_pt_0078_phi_0000_0000_0000_0000,
            cond_o => single_etmhf_i30
        );
    cond_single_etmhf_i9_i: entity work.combinatorial_conditions
        generic map(
            N_ETMHF_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_etmhf_bx_0_pt_00c8_phi_0000_0000_0000_0000,
            cond_o => single_etmhf_i9
        );
    cond_single_htt_i17_i: entity work.combinatorial_conditions
        generic map(
            N_HTT_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_htt_bx_0_pt_01e0_phi_0000_0000_0000_0000,
            cond_o => single_htt_i17
        );
    cond_single_htt_i18_i: entity work.combinatorial_conditions
        generic map(
            N_HTT_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_htt_bx_0_pt_01f4_phi_0000_0000_0000_0000,
            cond_o => single_htt_i18
        );
    cond_single_htt_i23_i: entity work.combinatorial_conditions
        generic map(
            N_HTT_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_htt_bx_0_pt_01b8_phi_0000_0000_0000_0000,
            cond_o => single_htt_i23
        );
    cond_single_htt_i25_i: entity work.combinatorial_conditions
        generic map(
            N_HTT_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_htt_bx_0_pt_0078_phi_0000_0000_0000_0000,
            cond_o => single_htt_i25
        );
    cond_single_htt_i31_i: entity work.combinatorial_conditions
        generic map(
            N_HTT_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_htt_bx_0_pt_0208_phi_0000_0000_0000_0000,
            cond_o => single_htt_i31
        );
    cond_single_mbt0_hfm_i27_i: entity work.combinatorial_conditions
        generic map(
            N_MBT0HFM_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_mbt0hfm_bx_0_count_0001,
            cond_o => single_mbt0_hfm_i27
        );
    cond_single_mbt0_hfp_i26_i: entity work.combinatorial_conditions
        generic map(
            N_MBT0HFP_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_mbt0hfp_bx_0_count_0001,
            cond_o => single_mbt0_hfp_i26
        );
    cond_double_mu_i19_i: entity work.combinatorial_conditions
        generic map(
            N_MU_OBJECTS, 2,
            ((0,7), (0,7), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_mu_bx_0_pt_0007_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_f000_charge_ign,
            comb_2 =>
            comb_mu_bx_0_pt_0007_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_f000_charge_ign,
            cond_o => double_mu_i19
        );
    cond_single_mu_i16_i: entity work.combinatorial_conditions
        generic map(
            N_MU_OBJECTS, 1,
            ((0,7), (0,0), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_mu_bx_0_pt_000d_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_f000_charge_ign,
            cond_o => single_mu_i16
        );    
    -- Centrality assignment
    -- External condition assignment  
    single_ext_i28 <= data.ext_cond(bx(0))(4);  
    single_ext_i39 <= data.ext_cond(bx(-2))(7);  
    single_ext_i40 <= data.ext_cond(bx(-1))(4);  
    single_ext_i41 <= data.ext_cond(bx(1))(4);  
    single_ext_i42 <= data.ext_cond(bx(2))(4);
    -- Instantiations of algorithms

-- 131 L1_Mu6_HTT240er : MU6[MU-QLTY_SNGL] AND HTT240
    l1_mu6_htt240er <= single_mu_i16 and single_htt_i17;
    algo(19) <= l1_mu6_htt240er;
-- 132 L1_Mu6_HTT250er : MU6[MU-QLTY_SNGL] AND HTT250
    l1_mu6_htt250er <= single_mu_i16 and single_htt_i18;
    algo(13) <= l1_mu6_htt250er;
-- 145 L1_DoubleMu3_SQ_ETMHF50_HTT60er : comb{MU3[MU-QLTY_SNGL],MU3[MU-QLTY_SNGL]} AND ETMHF50 AND HTT60
    l1_double_mu3_sq_etmhf50_htt60er <= double_mu_i19 and single_etmhf_i20 and single_htt_i25;
    algo(18) <= l1_double_mu3_sq_etmhf50_htt60er;
-- 146 L1_DoubleMu3_SQ_ETMHF50_Jet60er2p5_OR_DoubleJet40er2p5 : comb{MU3[MU-QLTY_SNGL],MU3[MU-QLTY_SNGL]} AND ETMHF50 AND (JET60[JET-ETA_2p52] OR comb{JET40[JET-ETA_2p52],JET40[JET-ETA_2p52]})
    l1_double_mu3_sq_etmhf50_jet60er2p5_or_double_jet40er2p5 <= double_mu_i19 and single_etmhf_i20 and ( single_jet_i21 or double_jet_i22 );
    algo(17) <= l1_double_mu3_sq_etmhf50_jet60er2p5_or_double_jet40er2p5;
-- 147 L1_DoubleMu3_SQ_ETMHF50_Jet60er2p5 : comb{MU3[MU-QLTY_SNGL],MU3[MU-QLTY_SNGL]} AND ETMHF50 AND JET60[JET-ETA_2p52]
    l1_double_mu3_sq_etmhf50_jet60er2p5 <= double_mu_i19 and single_etmhf_i20 and single_jet_i21;
    algo(20) <= l1_double_mu3_sq_etmhf50_jet60er2p5;
-- 148 L1_DoubleMu3_SQ_ETMHF60_Jet60er2p5 : comb{MU3[MU-QLTY_SNGL],MU3[MU-QLTY_SNGL]} AND ETMHF60 AND JET60[JET-ETA_2p52]
    l1_double_mu3_sq_etmhf60_jet60er2p5 <= double_mu_i19 and single_etmhf_i30 and single_jet_i21;
    algo(2) <= l1_double_mu3_sq_etmhf60_jet60er2p5;
-- 150 L1_DoubleMu3_SQ_HTT220er : comb{MU3[MU-QLTY_SNGL],MU3[MU-QLTY_SNGL]} AND HTT220
    l1_double_mu3_sq_htt220er <= double_mu_i19 and single_htt_i23;
    algo(6) <= l1_double_mu3_sq_htt220er;
-- 151 L1_DoubleMu3_SQ_HTT240er : comb{MU3[MU-QLTY_SNGL],MU3[MU-QLTY_SNGL]} AND HTT240
    l1_double_mu3_sq_htt240er <= double_mu_i19 and single_htt_i17;
    algo(7) <= l1_double_mu3_sq_htt240er;
-- 152 L1_DoubleMu3_SQ_HTT260er : comb{MU3[MU-QLTY_SNGL],MU3[MU-QLTY_SNGL]} AND HTT260
    l1_double_mu3_sq_htt260er <= double_mu_i19 and single_htt_i31;
    algo(12) <= l1_double_mu3_sq_htt260er;
-- 421 L1_ETMHF100 : ETMHF100
    l1_etmhf100 <= single_etmhf_i9;
    algo(0) <= l1_etmhf100;
-- 422 L1_ETMHF110 : ETMHF110
    l1_etmhf110 <= single_etmhf_i10;
    algo(14) <= l1_etmhf110;
-- 423 L1_ETMHF120 : ETMHF120
    l1_etmhf120 <= single_etmhf_i11;
    algo(9) <= l1_etmhf120;
-- 424 L1_ETMHF130 : ETMHF130
    l1_etmhf130 <= single_etmhf_i12;
    algo(1) <= l1_etmhf130;
-- 428 L1_ETMHF90_HTT60er : ETMHF90 AND HTT60
    l1_etmhf90_htt60er <= single_etmhf_i24 and single_htt_i25;
    algo(11) <= l1_etmhf90_htt60er;
-- 429 L1_ETMHF100_HTT60er : ETMHF100 AND HTT60
    l1_etmhf100_htt60er <= single_etmhf_i9 and single_htt_i25;
    algo(4) <= l1_etmhf100_htt60er;
-- 430 L1_ETMHF110_HTT60er : ETMHF110 AND HTT60
    l1_etmhf110_htt60er <= single_etmhf_i10 and single_htt_i25;
    algo(16) <= l1_etmhf110_htt60er;
-- 431 L1_ETMHF120_HTT60er : ETMHF120 AND HTT60
    l1_etmhf120_htt60er <= single_etmhf_i11 and single_htt_i25;
    algo(8) <= l1_etmhf120_htt60er;
-- 432 L1_ETMHF130_HTT60er : ETMHF130 AND HTT60
    l1_etmhf130_htt60er <= single_etmhf_i12 and single_htt_i25;
    algo(15) <= l1_etmhf130_htt60er;
-- 443 L1_ETMHF120_NotSecondBunchInTrain : ETMHF120 AND ((EXT_BPTX_OR_VME-2) OR ( NOT EXT_ZeroBias_BPTX_AND_VME-1) OR ( NOT EXT_ZeroBias_BPTX_AND_VME) OR ( NOT EXT_ZeroBias_BPTX_AND_VME+1) OR ( NOT EXT_ZeroBias_BPTX_AND_VME+2))
    l1_etmhf120_not_second_bunch_in_train <= single_etmhf_i11 and ( ( single_ext_i39 ) or ( not single_ext_i40 ) or ( not single_ext_i28 ) or ( not single_ext_i41 ) or ( not single_ext_i42 ) );
    algo(10) <= l1_etmhf120_not_second_bunch_in_train;
-- 444 L1_ETMHF110_HTT60er_NotSecondBunchInTrain : ETMHF110 AND HTT60 AND ((EXT_BPTX_OR_VME-2) OR ( NOT EXT_ZeroBias_BPTX_AND_VME-1) OR ( NOT EXT_ZeroBias_BPTX_AND_VME) OR ( NOT EXT_ZeroBias_BPTX_AND_VME+1) OR ( NOT EXT_ZeroBias_BPTX_AND_VME+2))
    l1_etmhf110_htt60er_not_second_bunch_in_train <= single_etmhf_i10 and single_htt_i25 and ( ( single_ext_i39 ) or ( not single_ext_i40 ) or ( not single_ext_i28 ) or ( not single_ext_i41 ) or ( not single_ext_i42 ) );
    algo(3) <= l1_etmhf110_htt60er_not_second_bunch_in_train;
-- 461 L1_MinimumBiasHF0_AND_BptxAND : (MBT0HFP1 AND MBT0HFM1) AND EXT_ZeroBias_BPTX_AND_VME
    l1_minimum_bias_hf0_and_bptx_and <= ( single_mbt0_hfp_i26 and single_mbt0_hfm_i27 ) and single_ext_i28;
    algo(5) <= l1_minimum_bias_hf0_and_bptx_and;

end architecture rtl;
