-- Description:
-- L1Menu logic generated by VHDL Producer:

-- Module ID: 0

-- Name of L1 Trigger Menu:
-- L1Menu_GTL_v2_x_y_test

-- Unique ID of L1 Trigger Menu:
-- 37d17afa-95d7-4e21-aaf2-5f8ccb7704c1

-- Unique ID of firmware implementation:
-- 09c6b402-4680-4a54-8ebb-880d6e4872bd

-- Scale set:
-- scales_2018_08_07

-- VHDL producer version
-- v2.4.0
-- ========================================================

library ieee;
use ieee.std_logic_1164.all;

use work.lhc_data_pkg.all;
use work.gtl_pkg.all;
use work.lut_pkg.all;
use work.l1menu_pkg.all;

entity l1menu is
    port(
        lhc_clk : in std_logic;
        data_in : in data_pipeline_record;
        conv_in : in conv_pipeline_record;
        algo : out std_logic_vector(NR_ALGOS-1 downto 0));
end l1menu;

architecture rtl of l1menu is

-- Calculations outputs
    signal cc_double : obj_bx_muon_cc_double_array;
    signal cc_triple : obj_bx_muon_cc_triple_array;
    signal cc_quad : obj_bx_muon_cc_quad_array;
    signal sub_eta_eg_jet : obj_bx_max_eta_range_array;
    signal deta_eg_jet : obj_bx_deta_dphi_vector_array;
    signal sub_phi_eg_jet : obj_bx_max_phi_range_array;
    signal dphi_eg_jet : obj_bx_deta_dphi_vector_array;
    signal dr_eg_jet : obj_bx_corr_cuts_std_logic_array;

-- Comparators outputs
    signal comp_pt_0001 : eg_obj_t;
    signal comp_pt_0005 : eg_obj_t;
    signal comp_pt_0006 : eg_obj_t;
    signal comp_pt_0002 : jet_obj_t;
    signal comp_pt_0003 : jet_obj_t;
    signal comp_pt_0007 : jet_obj_t;
    signal comp_eta_0002 : jet_obj_t;
    signal comp_eta_0001 : jet_obj_t;
    signal comp_eta_0003 : jet_obj_t;
    signal comp_pt_0004 : muon_obj_t;
    signal comp_qual_0002 : muon_obj_t;
    signal comp_qual_0001 : muon_obj_t;
    
    signal comp_dr_0001 : eg_jet_t;

    signal comp_cc_double_0001 : muon_cc_double_t;
    signal comp_cc_triple_0001 : muon_cc_triple_t;
    signal comp_cc_quad_0001 : muon_cc_quad_t;

-- Conditions inputs
    signal cond_in_0001 : eg_obj_t;
    signal cond_in_0002 : eg_obj_t;
    signal cond_in_0003 : eg_obj_t;
    signal cond_in_0005 : muon_cc_quad_t;
    signal cond_in_0006 : jet_obj_t;
    signal cond_in_0007 : jet_obj_t;
    signal cond_in_0008 : jet_obj_t;
    signal cond_in_0009 : jet_obj_t;
    signal cond_in_0010 : muon_obj_t;
    signal cond_in_0011 : muon_obj_t;
    signal cond_in_0012 : jet_obj_t;
    signal cond_in_0013 : eg_jet_t;

-- Conditions outputs
    signal double_eg_i2 : std_logic;
    signal single_jet_i3 : std_logic;
    signal single_jet_i4 : std_logic;
    signal single_jet_i5 : std_logic;
    signal single_jet_i6 : std_logic;
    signal double_mu_i0 : std_logic;
    signal quad_mu_i1 : std_logic;
    signal calo_calo_correlation_i7 : std_logic;
    signal calo_calo_correlation_i8 : std_logic;
    
-- Algorithms
    signal l1_quad_mu_open_os : std_logic;
    signal l1_double_mu0 : std_logic;
    signal l1_single_eg12_single_jet28_mid_eta2p7_min_dr0p4 : std_logic;
    signal l1_single_eg15_single_jet28_mid_eta2p7_min_dr0p4 : std_logic;
    signal l1_double_eg5 : std_logic;
    signal l1_single_jet60_fwd3p0 : std_logic;
    signal l1_single_jet120_fwd3p0 : std_logic;
    
begin

-- First stage: calculations

    muon_charge_correlations_0001_i: entity work.muon_charge_correlations
        port map(
            data_in.muon(bx(0)).charge,
            data_in.muon(bx(0)).charge,
            cc_double(bx(0),bx(0)),
            cc_triple(bx(0),bx(0)),
            cc_quad(bx(0),bx(0))
        );

    sub_eta_eg_jet_0001_i: entity work.sub_eta
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS
        )
        port map(
            conv_in.eg(bx(0)).eta,
            conv_in.jet(bx(0)).eta,
            sub_eta_eg_jet(bx(0),bx(0))
        );

    deta_eg_jet_0001_i: entity work.diff_eta_lut
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS, (eg_t,jet_t)
        )
        port map(
            sub_eta_eg_jet(bx(0),bx(0)),
            deta_eg_jet(bx(0),bx(0))
        );

    sub_phi_eg_jet_0001_i: entity work.sub_phi
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS,
            EG_JET_PHI_HALF_RANGE_BINS
        )
        port map(
            conv_in.eg(bx(0)).phi,
            conv_in.jet(bx(0)).phi,
            sub_phi_eg_jet(bx(0),bx(0))
        );

    dphi_eg_jet_0001_i: entity work.diff_phi_lut
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS, (eg_t,jet_t)
        )
        port map(
            sub_phi_eg_jet(bx(0),bx(0)),
            dphi_eg_jet(bx(0),bx(0))
        );

    dr_eg_jet_0001_i: entity work.delta_r
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS
        )
        port map(
            deta_eg_jet(bx(0),bx(0)),
            dphi_eg_jet(bx(0),bx(0)),
            dr_eg_jet(bx(0),bx(0))
        );
        
-- Second stage: comparisons

    comp_pt_0001_i: entity work.threshold_comparator
        generic map(
            N_OBJ => N_EG_OBJECTS,
            DATA_WIDTH => EG_PT_WIDTH,
            MODE => GE, -- default value
            THRESHOLD => X"000A"
        )
        port map(
            clk => lhc_clk,
            data => data_in.eg(bx(0)).pt,
--             comp_o => comp_eg_bx_0_pt_5
            comp_o => comp_pt_0001
        );

    comp_pt_0002_i: entity work.threshold_comparator
        generic map(
            N_OBJ => N_JET_OBJECTS,
            DATA_WIDTH => JET_PT_WIDTH,
            THRESHOLD => X"0078"
        )
        port map(
            clk => lhc_clk,
            data => data_in.jet(bx(0)).pt,
--             comp_o => comp_jet_bx_0_pt_60
            comp_o => comp_pt_0002
        );

    comp_eta_0001_i: entity work.range_comparator
        generic map(
            N_OBJ => N_JET_OBJECTS,
            DATA_WIDTH => JET_ETA_WIDTH,
            MODE => ETA,
            MIN_REQ => X"008D",
            MAX_REQ => X"00BA"
        )
        port map(
            clk => lhc_clk,
            data => data_in.jet(bx(0)).eta,
--             comp_o => comp_jet_bx_0_eta_3p00_NEG
            comp_o => comp_eta_0001
        );
        
    comp_eta_0002_i: entity work.range_comparator
        generic map(
            N_OBJ => N_JET_OBJECTS,
            DATA_WIDTH => JET_ETA_WIDTH,
            MODE => ETA,
            MIN_REQ => X"0045",
            MAX_REQ => X"0072"
        )
        port map(
            clk => lhc_clk,
            data => data_in.jet(bx(0)).eta,
--             comp_o => comp_jet_bx_0_eta_3p00_POS
            comp_o => comp_eta_0002
        );

    comp_pt_0003_i: entity work.threshold_comparator
        generic map(
            N_OBJ => N_JET_OBJECTS,
            DATA_WIDTH => JET_PT_WIDTH,
            THRESHOLD => X"00F0"
        )
        port map(
            clk => lhc_clk,
            data => data_in.jet(bx(0)).pt,
--             comp_o => comp_jet_bx_0_pt_120
            comp_o => comp_pt_0003
        );

    comp_pt_0004_i: entity work.threshold_comparator
        generic map(
            N_OBJ => N_MUON_OBJECTS,
            DATA_WIDTH => MUON_PT_WIDTH,
            THRESHOLD => X"0001"
        )
        port map(
            clk => lhc_clk,
            data => data_in.muon(bx(0)).pt,
--             comp_o => comp_muon_bx_0_pt_0
            comp_o => comp_pt_0004
        );

    comp_qual_0001_i: entity work.lut_comparator
        generic map(
            N_OBJ => N_MUON_OBJECTS,
            DATA_WIDTH => MUON_QUAL_WIDTH,
            LUT => X"FF00"
        )
        port map(
            clk => lhc_clk,
            data => data_in.muon(bx(0)).qual,
--             comp_o => comp_muon_bx_0_qual_QLTY_DBLE
            comp_o => comp_qual_0001
        );

    comp_qual_0002_i: entity work.lut_comparator
        generic map(
            N_OBJ => N_MUON_OBJECTS,
            DATA_WIDTH => MUON_QUAL_WIDTH,
            LUT => X"FFF0"
        )
        port map(
            clk => lhc_clk,
            data => data_in.muon(bx(0)).qual,
--             comp_o => comp_muon_bx_0_qual_QLTY_OPEN
            comp_o => comp_qual_0002
        );

    comp_pt_0005_i: entity work.threshold_comparator
        generic map(
            N_OBJ => N_EG_OBJECTS,
            DATA_WIDTH => EG_PT_WIDTH,
            THRESHOLD => X"0018"
        )
        port map(
            clk => lhc_clk,
            data => data_in.eg(bx(0)).pt,
--             comp_o => comp_eg_bx_0_pt_12
            comp_o => comp_pt_0005
        );

    comp_pt_0006_i: entity work.threshold_comparator
        generic map(
            N_OBJ => N_EG_OBJECTS,
            DATA_WIDTH => EG_PT_WIDTH,
            THRESHOLD => X"001E"
        )
        port map(
            clk => lhc_clk,
            data => data_in.eg(bx(0)).pt,
--             comp_o => comp_eg_bx_0_pt_15
            comp_o => comp_pt_0006
        );

    comp_pt_0007_i: entity work.threshold_comparator
        generic map(
            N_OBJ => N_JET_OBJECTS,
            DATA_WIDTH => JET_PT_WIDTH,
            THRESHOLD => X"0038"
        )
        port map(
            clk => lhc_clk,
            data => data_in.jet(bx(0)).pt,
--             comp_o => comp_jet_bx_0_pt_28
            comp_o => comp_pt_0007
        );

    comp_eta_0003_i: entity work.range_comparator
        generic map(
            N_OBJ => N_JET_OBJECTS,
            DATA_WIDTH => JET_ETA_WIDTH,
            MODE => ETA,
            MIN_REQ => X"00C2",
            MAX_REQ => X"003D"
        )
        port map(
            clk => lhc_clk,
            data => data_in.jet(bx(0)).eta,
--             comp_o => comp_jet_bx_0_eta_2p7
            comp_o => comp_eta_0003
        );

    comp_dr_0001_i: entity work.comparators_corr_cuts
        generic map(
            N_OBJ_1 => N_EG_OBJECTS,
            N_OBJ_2 => N_JET_OBJECTS,
            DATA_WIDTH => 2*DETA_DPHI_VECTOR_WIDTH,
            MODE => deltaR,
            MIN_REQ => X"0000000027100",
            MAX_REQ => X"00000084CA240"
        )
        port map(
            clk => lhc_clk,
            data => dr_eg_jet(bx(0),bx(0)),
--             comp_o => comp_dr_eg_bx_0_jet_bx_0_req_DR_MIN_0p4
            comp_o => comp_dr_0001
        );

    comp_cc_0001_i: entity work.comparator_muon_charge_corr
        generic map(
            REQ => CC_OS
        )
        port map(
            clk => lhc_clk,
            cc_double => cc_double(bx(0),bx(0)),
            cc_triple => cc_triple(bx(0),bx(0)),
            cc_quad => cc_quad(bx(0),bx(0)),
--             comp_o_double => comp_cc_double_bx_0_bx_0_OS,
--             comp_o_triple => comp_cc_triple_bx_0_bx_0_OS,
--             comp_o_quad => comp_cc_quad_bx_0_bx_0_OS
            comp_o_double => comp_cc_double_0001,
            comp_o_triple => comp_cc_triple_0001,
            comp_o_quad => comp_cc_quad_0001
        );
        
    -- Creating condition inputs
    
    cond_in_0001 <= comp_pt_0001;
    cond_in_0002 <= comp_pt_0005;
    cond_in_0003 <= comp_pt_0006;
    cond_in_0005 <= comp_cc_quad_0001;    
    cond_in_0006 <= comp_pt_0002 and comp_eta_0001;
    cond_in_0007 <= comp_pt_0002 and comp_eta_0002;
    cond_in_0008 <= comp_pt_0003 and comp_eta_0001;
    cond_in_0009 <= comp_pt_0003 and comp_eta_0002;
    cond_in_0010 <= comp_pt_0004 and comp_qual_0001;
    cond_in_0011 <= comp_pt_0004 and comp_qual_0002;
    cond_in_0012 <= comp_pt_0007 and comp_eta_0003;
    cond_in_0013 <= comp_dr_0001;
        
-- Third stage: conditions and algos
    
    -- Instantiations of conditions
    
    double_eg_i2_i: entity work.combinatorial_conditions
        generic map(
            N_OBJ => N_EG_OBJECTS,
            N_REQ => 2,
            SLICES => ((0,11),(0,11),(0,0),(0,0)),
            TBPT_SEL => false,
            CHARGE_CORR_SEL => false
        )
        port map(
            clk => lhc_clk,
            in_1 => cond_in_0001,
            in_2 => cond_in_0001,
            cond_o => double_eg_i2
        );

    single_jet_i3_i: entity work.combinatorial_conditions
        generic map(
            N_OBJ => N_JET_OBJECTS,
            N_REQ => 1,
            SLICES => ((0,11),(0,0),(0,0),(0,0)),
            TBPT_SEL => false,
            CHARGE_CORR_SEL => false
        )
        port map(
            clk => lhc_clk,
            in_1 => cond_in_0006,
            cond_o => single_jet_i3
        );

    single_jet_i4_i: entity work.combinatorial_conditions
        generic map(
            N_OBJ => N_JET_OBJECTS,
            N_REQ => 1,
            SLICES => ((0,11),(0,0),(0,0),(0,0)),
            TBPT_SEL => false,
            CHARGE_CORR_SEL => false
        )
        port map(
            clk => lhc_clk,
            in_1 => cond_in_0007,
            cond_o => single_jet_i4
        );

    single_jet_i5_i: entity work.combinatorial_conditions
        generic map(
            N_OBJ => N_JET_OBJECTS,
            N_REQ => 1,
            SLICES => ((0,11),(0,0),(0,0),(0,0)),
            TBPT_SEL => false,
            CHARGE_CORR_SEL => false
        )
        port map(
            clk => lhc_clk,
            in_1 => cond_in_0008,
            cond_o => single_jet_i5
        );

    single_jet_i6_i: entity work.combinatorial_conditions
        generic map(
            N_OBJ => N_JET_OBJECTS,
            N_REQ => 1,
            SLICES => ((0,11),(0,0),(0,0),(0,0)),
            TBPT_SEL => false,
            CHARGE_CORR_SEL => false
        )
        port map(
            clk => lhc_clk,
            in_1 => cond_in_0009,
            cond_o => single_jet_i6
        );

    double_mu_i0_i: entity work.combinatorial_conditions
        generic map(
            N_OBJ => N_MUON_OBJECTS,
            N_REQ => 2,
            SLICES => ((0,7),(0,7),(0,0),(0,0)),
            TBPT_SEL => false,
            CHARGE_CORR_SEL => false
        )
        port map(
            clk => lhc_clk,
            in_1 => cond_in_0010,
            in_2 => cond_in_0010,
            cond_o => double_mu_i0
        );

    quad_mu_i1_i: entity work.combinatorial_conditions
        generic map(
            N_OBJ => N_MUON_OBJECTS,
            N_REQ => 4,
            SLICES => ((0,7),(0,7),(0,7),(0,7)),
            TBPT_SEL => false,
            CHARGE_CORR_SEL => true
        )
        port map(
            clk => lhc_clk,
            in_1 => cond_in_0011,
            in_2 => cond_in_0011,
            in_3 => cond_in_0011,
            in_4 => cond_in_0011,
            charge_corr_quad => cond_in_0005,
            cond_o => quad_mu_i1
        );

    calo_calo_correlation_i7_i: entity work.correlation_conditions
        generic map(
            N_OBJ_1 => N_EG_OBJECTS,
            N_OBJ_2 => N_JET_OBJECTS,
            SLICES => ((0,11),(0,11),(0,0),(0,0)),
            DETA_SEL => false,
            DPHI_SEL => false,
            DR_SEL => true,
            INV_MASS_SEL => false,
            TRANS_MASS_SEL => false,
            TBPT_SEL => false,
            CHARGE_CORR_SEL => false
        )
        port map(
            clk => lhc_clk,
            in_1 => cond_in_0002,
            in_2 => cond_in_0012,
            delta_r => cond_in_0013,
            cond_o => calo_calo_correlation_i7
        );

    calo_calo_correlation_i8_i: entity work.correlation_conditions
        generic map(
            N_OBJ_1 => N_EG_OBJECTS,
            N_OBJ_2 => N_JET_OBJECTS,
            SLICES => ((0,11),(0,11),(0,0),(0,0)),
            DETA_SEL => false,
            DPHI_SEL => false,
            DR_SEL => true,
            INV_MASS_SEL => false,
            TRANS_MASS_SEL => false,
            TBPT_SEL => false,
            CHARGE_CORR_SEL => false
        )
        port map(
            clk => lhc_clk,
            in_1 => cond_in_0003,
            in_2 => cond_in_0012,
            delta_r => cond_in_0013,
            cond_o => calo_calo_correlation_i8
        );

    -- Instantiations of algorithms

    -- 0 L1_QuadMuOpen_OS : comb{MU0[MU-QLTY_OPEN],MU0[MU-QLTY_OPEN],MU0[MU-QLTY_OPEN],MU0[MU-QLTY_OPEN]}[CHGCOR_OS]
    l1_quad_mu_open_os <= quad_mu_i1;
    algo(2) <= l1_quad_mu_open_os;

    -- 1 L1_DoubleMu0 : comb{MU0[MU-QLTY_DBLE],MU0[MU-QLTY_DBLE]}
    l1_double_mu0 <= double_mu_i0;
    algo(3) <= l1_double_mu0;

    -- 2 L1_SingleEG12_SingleJet28_MidEta2p7_MinDr0p4 : dist{EG12,JET28[JET-ETA_2p7]}[DR_MIN_0p4]
    l1_single_eg12_single_jet28_mid_eta2p7_min_dr0p4 <= calo_calo_correlation_i7;
    algo(0) <= l1_single_eg12_single_jet28_mid_eta2p7_min_dr0p4;

    -- 3 L1_SingleEG15_SingleJet28_MidEta2p7_MinDr0p4 : dist{EG15,JET28[JET-ETA_2p7]}[DR_MIN_0p4]
    l1_single_eg15_single_jet28_mid_eta2p7_min_dr0p4 <= calo_calo_correlation_i8;
    algo(1) <= l1_single_eg15_single_jet28_mid_eta2p7_min_dr0p4;

    -- 4 L1_DoubleEG5 : comb{EG5,EG5}
    l1_double_eg5 <= double_eg_i2;
    algo(4) <= l1_double_eg5;

    -- 5 L1_SingleJet60_FWD3p0 : JET60[JET-ETA_FWD_3p00_NEG] OR JET60[JET-ETA_FWD_3p00_POS]
    l1_single_jet60_fwd3p0 <= single_jet_i3 or single_jet_i4;
    algo(6) <= l1_single_jet60_fwd3p0;

    -- 6 L1_SingleJet120_FWD3p0 : JET120[JET-ETA_FWD_3p00_NEG] OR JET120[JET-ETA_FWD_3p00_POS]
    l1_single_jet120_fwd3p0 <= single_jet_i5 or single_jet_i6;
    algo(5) <= l1_single_jet120_fwd3p0;

end architecture rtl;

