-- Description:
-- L1Menu logic generated by VHDL Producer:

-- ========================================================
-- from VHDL producer:

-- Module ID: 3

-- Name of L1 Trigger Menu:
-- L1Menu_test_esums_instances_v1

-- Unique ID of L1 Trigger Menu:
-- f7b5ee69-e72e-4011-aa54-9fdcb44159a6

-- Unique ID of firmware implementation:
-- 0f60d609-97a3-4ed7-b9ca-23c30a19b2c6

-- Scale set:
-- scales_2017_05_23

-- VHDL producer version
-- v3.1.1
-- ========================================================

library ieee;
use ieee.std_logic_1164.all;

use work.lhc_data_pkg.all;
use work.gtl_pkg.all;
use work.lut_pkg.all;
use work.l1menu_pkg.all;

entity l1menu is
    port(
        lhc_clk : in std_logic;
        data : in data_pipeline_record;
        conv : in conv_pipeline_record;
        algo : out std_logic_vector(NR_ALGOS-1 downto 0));
end l1menu;

architecture rtl of l1menu is
-- Calculations outputs
    -- Differences
    -- Correlation cuts
    -- Muon charge correlation    
    signal cc_double : obj_bx_muon_cc_double_array;
    signal cc_triple : obj_bx_muon_cc_triple_array;
    signal cc_quad : obj_bx_muon_cc_quad_array;
-- Comparators outputs
    -- Object cuts
    signal comp_pt_jet_bx_0_0x008c : jet_obj_t;
    signal comp_eta_jet_bx_0_0x00c9_0x0036 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x006e : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0050 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x00a0 : jet_obj_t;
    signal comp_eta_jet_bx_0_0x00cf_0x0030 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0078 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x005a : jet_obj_t;
    signal comp_eta_jet_bx_0_0x00cb_0x0034 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0064 : jet_obj_t;
    signal comp_pt_etmhf_bx_0_0x0118 : etmhf_obj_t;
    signal comp_pt_htt_bx_0_0x00f0 : htt_obj_t;
    signal comp_pt_htt_bx_0_0x0280 : htt_obj_t;
-- Correlation cuts
-- Muon charge correlation
-- Conditions inputs
    -- Object cuts "and"
   signal comb_jet_bx_0_pt_008c_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_006e_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0050_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_00a0_eta_00cf_0030_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0078_eta_00cf_0030_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_005a_eta_00cb_0034_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0050_eta_00cb_0034_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0064_eta_00cb_0034_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_etmhf_bx_0_pt_0118_phi_0000_0000_0000_0000 : etmhf_obj_t;
   signal comb_htt_bx_0_pt_00f0_phi_0000_0000_0000_0000 : htt_obj_t;
   signal comb_htt_bx_0_pt_0280_phi_0000_0000_0000_0000 : htt_obj_t;
-- Signal definition for conditions names
    signal single_etmhf_i32 : std_logic;
    signal single_htt_i0 : std_logic;
    signal single_htt_i5 : std_logic;
    signal quad_jet_i14 : std_logic;
    signal quad_jet_i15 : std_logic;
    signal quad_jet_i29 : std_logic;
-- Signal definition for algorithms names
    signal l1_htt320er_quad_jet_70_55_40_40_er2p4 : std_logic;
    signal l1_htt320er_quad_jet_80_60_er2p1_45_40_er2p3 : std_logic;
    signal l1_htt320er_quad_jet_80_60_er2p1_50_45_er2p3 : std_logic;
    signal l1_htt120er : std_logic;
    signal l1_htt320er : std_logic;
    signal l1_etmhf140 : std_logic;
begin
-- First stage: calculations
    
-- Second stage: comparisons
    comp_pt_jet_bx_0_0x008c_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"008C", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x008c
        );
    comp_eta_jet_bx_0_0x00c9_0x0036_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_ETA_WIDTH,
            ETA, X"00C9", X"0036", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).eta, comp_eta_jet_bx_0_0x00c9_0x0036
        );
    comp_pt_jet_bx_0_0x006e_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"006E", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x006e
        );
    comp_pt_jet_bx_0_0x0050_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0050", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0050
        );
    comp_pt_jet_bx_0_0x00a0_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"00A0", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x00a0
        );
    comp_eta_jet_bx_0_0x00cf_0x0030_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_ETA_WIDTH,
            ETA, X"00CF", X"0030", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).eta, comp_eta_jet_bx_0_0x00cf_0x0030
        );
    comp_pt_jet_bx_0_0x0078_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0078", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0078
        );
    comp_pt_jet_bx_0_0x005a_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"005A", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x005a
        );
    comp_eta_jet_bx_0_0x00cb_0x0034_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_ETA_WIDTH,
            ETA, X"00CB", X"0034", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).eta, comp_eta_jet_bx_0_0x00cb_0x0034
        );
    comp_pt_jet_bx_0_0x0064_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0064", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0064
        );
    comp_pt_etmhf_bx_0_0x0118_i: entity work.comparators_obj_cuts
        generic map(
            N_ETMHF_OBJECTS, ETMHF_PT_WIDTH,  
            GE,  
            X"0118", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.etmhf(bx(0)).pt, comp_pt_etmhf_bx_0_0x0118
        );
    comp_pt_htt_bx_0_0x00f0_i: entity work.comparators_obj_cuts
        generic map(
            N_HTT_OBJECTS, HTT_PT_WIDTH,  
            GE,  
            X"00F0", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.htt(bx(0)).pt, comp_pt_htt_bx_0_0x00f0
        );
    comp_pt_htt_bx_0_0x0280_i: entity work.comparators_obj_cuts
        generic map(
            N_HTT_OBJECTS, HTT_PT_WIDTH,  
            GE,  
            X"0280", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.htt(bx(0)).pt, comp_pt_htt_bx_0_0x0280
        );

-- Third stage: conditions and algos
    -- Creating condition inputs (combination of object cuts)
    comb_jet_bx_0_pt_008c_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x008c
    and 
    (
    comp_eta_jet_bx_0_0x00c9_0x0036
    )
    ;

    comb_jet_bx_0_pt_006e_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x006e
    and 
    (
    comp_eta_jet_bx_0_0x00c9_0x0036
    )
    ;

    comb_jet_bx_0_pt_0050_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0050
    and 
    (
    comp_eta_jet_bx_0_0x00c9_0x0036
    )
    ;

    comb_jet_bx_0_pt_00a0_eta_00cf_0030_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x00a0
    and 
    (
    comp_eta_jet_bx_0_0x00cf_0x0030
    )
    ;

    comb_jet_bx_0_pt_0078_eta_00cf_0030_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0078
    and 
    (
    comp_eta_jet_bx_0_0x00cf_0x0030
    )
    ;

    comb_jet_bx_0_pt_005a_eta_00cb_0034_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x005a
    and 
    (
    comp_eta_jet_bx_0_0x00cb_0x0034
    )
    ;

    comb_jet_bx_0_pt_0050_eta_00cb_0034_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0050
    and 
    (
    comp_eta_jet_bx_0_0x00cb_0x0034
    )
    ;

    comb_jet_bx_0_pt_0064_eta_00cb_0034_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0064
    and 
    (
    comp_eta_jet_bx_0_0x00cb_0x0034
    )
    ;

    comb_etmhf_bx_0_pt_0118_phi_0000_0000_0000_0000 <= 
    comp_pt_etmhf_bx_0_0x0118
    ;

    comb_htt_bx_0_pt_00f0_phi_0000_0000_0000_0000 <= 
    comp_pt_htt_bx_0_0x00f0
    ;

    comb_htt_bx_0_pt_0280_phi_0000_0000_0000_0000 <= 
    comp_pt_htt_bx_0_0x0280
    ;

    -- Instantiations of conditions
    cond_quad_jet_i14_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 4,
            ((0,11), (0,11), (0,11), (0,11)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_008c_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_006e_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_0_pt_0050_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_jet_bx_0_pt_0050_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => quad_jet_i14
        );
    cond_quad_jet_i15_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 4,
            ((0,11), (0,11), (0,11), (0,11)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_00a0_eta_00cf_0030_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_0078_eta_00cf_0030_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_0_pt_005a_eta_00cb_0034_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_jet_bx_0_pt_0050_eta_00cb_0034_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => quad_jet_i15
        );
    cond_quad_jet_i29_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 4,
            ((0,11), (0,11), (0,11), (0,11)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_00a0_eta_00cf_0030_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_0078_eta_00cf_0030_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_0_pt_0064_eta_00cb_0034_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_jet_bx_0_pt_005a_eta_00cb_0034_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => quad_jet_i29
        );
    cond_single_etmhf_i32_i: entity work.combinatorial_conditions
        generic map(
            N_ETMHF_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_etmhf_bx_0_pt_0118_phi_0000_0000_0000_0000,
            cond_o => single_etmhf_i32
        );
    cond_single_htt_i0_i: entity work.combinatorial_conditions
        generic map(
            N_HTT_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_htt_bx_0_pt_00f0_phi_0000_0000_0000_0000,
            cond_o => single_htt_i0
        );
    cond_single_htt_i5_i: entity work.combinatorial_conditions
        generic map(
            N_HTT_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_htt_bx_0_pt_0280_phi_0000_0000_0000_0000,
            cond_o => single_htt_i5
        );    
    -- Centrality assignment
    -- External condition assignment
    -- Instantiations of algorithms

-- 385 L1_HTT320er_QuadJet_70_55_40_40_er2p4 : HTT320 AND comb{JET70[JET-ETA_2p4],JET55[JET-ETA_2p4],JET40[JET-ETA_2p4],JET40[JET-ETA_2p4]}
    l1_htt320er_quad_jet_70_55_40_40_er2p4 <= single_htt_i5 and quad_jet_i14;
    algo(3) <= l1_htt320er_quad_jet_70_55_40_40_er2p4;
-- 386 L1_HTT320er_QuadJet_80_60_er2p1_45_40_er2p3 : HTT320 AND comb{JET80[JET-ETA_2p13],JET60[JET-ETA_2p13],JET45[JET-ETA_2p3],JET40[JET-ETA_2p3]}
    l1_htt320er_quad_jet_80_60_er2p1_45_40_er2p3 <= single_htt_i5 and quad_jet_i15;
    algo(5) <= l1_htt320er_quad_jet_80_60_er2p1_45_40_er2p3;
-- 387 L1_HTT320er_QuadJet_80_60_er2p1_50_45_er2p3 : HTT320 AND comb{JET80[JET-ETA_2p13],JET60[JET-ETA_2p13],JET50[JET-ETA_2p3],JET45[JET-ETA_2p3]}
    l1_htt320er_quad_jet_80_60_er2p1_50_45_er2p3 <= single_htt_i5 and quad_jet_i29;
    algo(4) <= l1_htt320er_quad_jet_80_60_er2p1_50_45_er2p3;
-- 398 L1_HTT120er : HTT120
    l1_htt120er <= single_htt_i0;
    algo(1) <= l1_htt120er;
-- 403 L1_HTT320er : HTT320
    l1_htt320er <= single_htt_i5;
    algo(2) <= l1_htt320er;
-- 425 L1_ETMHF140 : ETMHF140
    l1_etmhf140 <= single_etmhf_i32;
    algo(0) <= l1_etmhf140;

end architecture rtl;
