-- Description:
-- L1Menu logic generated by VHDL Producer:

-- ========================================================
-- from VHDL producer:

-- Module ID: 1

-- Name of L1 Trigger Menu:
-- L1Menu_test_esums_instances_v1

-- Unique ID of L1 Trigger Menu:
-- f7b5ee69-e72e-4011-aa54-9fdcb44159a6

-- Unique ID of firmware implementation:
-- 0f60d609-97a3-4ed7-b9ca-23c30a19b2c6

-- Scale set:
-- scales_2017_05_23

-- VHDL producer version
-- v3.1.1
-- ========================================================

library ieee;
use ieee.std_logic_1164.all;

use work.lhc_data_pkg.all;
use work.gtl_pkg.all;
use work.lut_pkg.all;
use work.l1menu_pkg.all;

entity l1menu is
    port(
        lhc_clk : in std_logic;
        data : in data_pipeline_record;
        conv : in conv_pipeline_record;
        algo : out std_logic_vector(NR_ALGOS-1 downto 0));
end l1menu;

architecture rtl of l1menu is
-- Calculations outputs
    -- Differences
    -- Correlation cuts
    -- Muon charge correlation    
    signal cc_double : obj_bx_muon_cc_double_array;
    signal cc_triple : obj_bx_muon_cc_triple_array;
    signal cc_quad : obj_bx_muon_cc_quad_array;
-- Comparators outputs
    -- Object cuts
    signal comp_pt_jet_bx_0_0x008c : jet_obj_t;
    signal comp_eta_jet_bx_0_0x00c9_0x0036 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x006e : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0050 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0046 : jet_obj_t;
    signal comp_pt_etm_bx_0_0x012c : etm_obj_t;
    signal comp_pt_ett_bx_0_0x0fa0 : ett_obj_t;
    signal comp_pt_htt_bx_0_0x0230 : htt_obj_t;
-- Correlation cuts
-- Muon charge correlation
-- Conditions inputs
    -- Object cuts "and"
   signal comb_jet_bx_0_pt_008c_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_006e_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0050_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0046_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_etm_bx_0_pt_012c_phi_0000_0000_0000_0000 : etm_obj_t;
   signal comb_ett_bx_0_pt_0fa0_phi_0000_0000_0000_0000 : ett_obj_t;
   signal comb_htt_bx_0_pt_0230_phi_0000_0000_0000_0000 : htt_obj_t;
-- Signal definition for conditions names
    signal single_etm_i35 : std_logic;
    signal single_ett_i38 : std_logic;
    signal single_htt_i4 : std_logic;
    signal quad_jet_i13 : std_logic;
-- Signal definition for algorithms names
    signal l1_htt280er_quad_jet_70_55_40_35_er2p4 : std_logic;
    signal l1_htt280er : std_logic;
    signal l1_ett2000 : std_logic;
    signal l1_etm150 : std_logic;
begin
-- First stage: calculations
    
-- Second stage: comparisons
    comp_pt_jet_bx_0_0x008c_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"008C", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x008c
        );
    comp_eta_jet_bx_0_0x00c9_0x0036_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_ETA_WIDTH,
            ETA, X"00C9", X"0036", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).eta, comp_eta_jet_bx_0_0x00c9_0x0036
        );
    comp_pt_jet_bx_0_0x006e_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"006E", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x006e
        );
    comp_pt_jet_bx_0_0x0050_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0050", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0050
        );
    comp_pt_jet_bx_0_0x0046_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0046", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0046
        );
    comp_pt_etm_bx_0_0x012c_i: entity work.comparators_obj_cuts
        generic map(
            N_ETM_OBJECTS, ETM_PT_WIDTH,  
            GE,  
            X"012C", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.etm(bx(0)).pt, comp_pt_etm_bx_0_0x012c
        );
    comp_pt_ett_bx_0_0x0fa0_i: entity work.comparators_obj_cuts
        generic map(
            N_ETT_OBJECTS, ETT_PT_WIDTH,  
            GE,  
            X"0FA0", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.ett(bx(0)).pt, comp_pt_ett_bx_0_0x0fa0
        );
    comp_pt_htt_bx_0_0x0230_i: entity work.comparators_obj_cuts
        generic map(
            N_HTT_OBJECTS, HTT_PT_WIDTH,  
            GE,  
            X"0230", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.htt(bx(0)).pt, comp_pt_htt_bx_0_0x0230
        );

-- Third stage: conditions and algos
    -- Creating condition inputs (combination of object cuts)
    comb_jet_bx_0_pt_008c_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x008c
    and 
    (
    comp_eta_jet_bx_0_0x00c9_0x0036
    )
    ;

    comb_jet_bx_0_pt_006e_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x006e
    and 
    (
    comp_eta_jet_bx_0_0x00c9_0x0036
    )
    ;

    comb_jet_bx_0_pt_0050_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0050
    and 
    (
    comp_eta_jet_bx_0_0x00c9_0x0036
    )
    ;

    comb_jet_bx_0_pt_0046_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0046
    and 
    (
    comp_eta_jet_bx_0_0x00c9_0x0036
    )
    ;

    comb_etm_bx_0_pt_012c_phi_0000_0000_0000_0000 <= 
    comp_pt_etm_bx_0_0x012c
    ;

    comb_ett_bx_0_pt_0fa0_phi_0000_0000_0000_0000 <= 
    comp_pt_ett_bx_0_0x0fa0
    ;

    comb_htt_bx_0_pt_0230_phi_0000_0000_0000_0000 <= 
    comp_pt_htt_bx_0_0x0230
    ;

    -- Instantiations of conditions
    cond_quad_jet_i13_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 4,
            ((0,11), (0,11), (0,11), (0,11)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_008c_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_006e_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_0_pt_0050_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_jet_bx_0_pt_0046_eta_00c9_0036_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => quad_jet_i13
        );
    cond_single_etm_i35_i: entity work.combinatorial_conditions
        generic map(
            N_ETM_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_etm_bx_0_pt_012c_phi_0000_0000_0000_0000,
            cond_o => single_etm_i35
        );
    cond_single_ett_i38_i: entity work.combinatorial_conditions
        generic map(
            N_ETT_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_ett_bx_0_pt_0fa0_phi_0000_0000_0000_0000,
            cond_o => single_ett_i38
        );
    cond_single_htt_i4_i: entity work.combinatorial_conditions
        generic map(
            N_HTT_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_htt_bx_0_pt_0230_phi_0000_0000_0000_0000,
            cond_o => single_htt_i4
        );    
    -- Centrality assignment
    -- External condition assignment
    -- Instantiations of algorithms

-- 384 L1_HTT280er_QuadJet_70_55_40_35_er2p4 : HTT280 AND comb{JET70[JET-ETA_2p4],JET55[JET-ETA_2p4],JET40[JET-ETA_2p4],JET35[JET-ETA_2p4]}
    l1_htt280er_quad_jet_70_55_40_35_er2p4 <= single_htt_i4 and quad_jet_i13;
    algo(3) <= l1_htt280er_quad_jet_70_55_40_35_er2p4;
-- 402 L1_HTT280er : HTT280
    l1_htt280er <= single_htt_i4;
    algo(2) <= l1_htt280er;
-- 412 L1_ETT2000 : ETT2000
    l1_ett2000 <= single_ett_i38;
    algo(1) <= l1_ett2000;
-- 417 L1_ETM150 : ETM150
    l1_etm150 <= single_etm_i35;
    algo(0) <= l1_etm150;

end architecture rtl;
