-- Description:
-- L1Menu logic generated by VHDL Producer:

-- ========================================================
-- from VHDL producer:

-- Module ID: 0

-- Name of L1 Trigger Menu:
-- L1Menu_test_compare_gtl_struct_v7

-- Unique ID of L1 Trigger Menu:
-- c2577a01-8fb4-4ced-9e9e-100c8cb51099

-- Unique ID of firmware implementation:
-- e9b3f413-1690-4dd2-9445-b2c6732016ee

-- Scale set:
-- scales_2018_08_07

-- VHDL producer version
-- v2.4.0
-- ========================================================

library ieee;
use ieee.std_logic_1164.all;

use work.lhc_data_pkg.all;
use work.gtl_pkg.all;
use work.lut_pkg.all;
use work.l1menu_pkg.all;

entity l1menu is
    port(
        lhc_clk : in std_logic;
        data : in data_pipeline_record;
        conv : in conv_pipeline_record;
        algo : out std_logic_vector(NR_ALGOS-1 downto 0));
end l1menu;

architecture rtl of l1menu is
-- Calculations outputs
    -- Differences
    signal deta_calc_eg_jet : obj_bx_max_eta_range_array;
    signal deta_calc_jet_jet : obj_bx_max_eta_range_array;
    signal deta_calc_jet_tau : obj_bx_max_eta_range_array;
    signal deta_calc_jet_mu : obj_bx_max_eta_range_array;
    signal dphi_calc_eg_jet : obj_bx_max_phi_range_array;
    signal dphi_calc_jet_jet : obj_bx_max_phi_range_array;
    signal dphi_calc_jet_tau : obj_bx_max_phi_range_array;
    signal dphi_calc_jet_mu : obj_bx_max_phi_range_array;
    -- Correlation cuts
    signal dr_eg_jet :  obj_bx_corr_cuts_std_logic_array;
    signal deta_jet_jet :  obj_bx_corr_cuts_std_logic_array;
    signal invmass_jet_jet :  obj_bx_corr_cuts_std_logic_array;
    signal dr_jet_mu :  obj_bx_corr_cuts_std_logic_array;
    signal dr_jet_tau :  obj_bx_corr_cuts_std_logic_array;
    signal deta_eg_jet :  obj_bx_corr_cuts_std_logic_array;
    signal deta_jet_tau :  obj_bx_corr_cuts_std_logic_array;
    signal deta_jet_mu :  obj_bx_corr_cuts_std_logic_array;
    signal dphi_eg_jet :  obj_bx_corr_cuts_std_logic_array;
    signal dphi_jet_jet :  obj_bx_corr_cuts_std_logic_array;
    signal dphi_jet_tau :  obj_bx_corr_cuts_std_logic_array;
    signal dphi_jet_mu :  obj_bx_corr_cuts_std_logic_array;
    signal cosh_deta_eg_jet :  obj_bx_corr_cuts_std_logic_array;
    signal cosh_deta_jet_jet :  obj_bx_corr_cuts_std_logic_array;
    signal cosh_deta_jet_tau :  obj_bx_corr_cuts_std_logic_array;
    signal cosh_deta_jet_mu :  obj_bx_corr_cuts_std_logic_array;
    signal cos_dphi_eg_jet :  obj_bx_corr_cuts_std_logic_array;
    signal cos_dphi_jet_jet :  obj_bx_corr_cuts_std_logic_array;
    signal cos_dphi_jet_tau :  obj_bx_corr_cuts_std_logic_array;
    signal cos_dphi_jet_mu :  obj_bx_corr_cuts_std_logic_array;
    -- Muon charge correlation    
    signal cc_double : obj_bx_muon_cc_double_array;
    signal cc_triple : obj_bx_muon_cc_triple_array;
    signal cc_quad : obj_bx_muon_cc_quad_array;
-- Comparators outputs
    -- Object cuts
    signal comp_pt_eg_bx_0_0x000a : eg_obj_t;
    signal comp_pt_jet_bx_0_0x0096 : jet_obj_t;
    signal comp_eta_jet_bx_0_0x00c6_0x0039 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0082 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x00c8 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x003c : jet_obj_t;
    signal comp_pt_jet_bx_0_0x00dc : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0046 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x00be : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0028 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x0078 : jet_obj_t;
    signal comp_eta_jet_bx_0_0x008d_0x00ba : jet_obj_t;
    signal comp_eta_jet_bx_0_0x0045_0x0072 : jet_obj_t;
    signal comp_pt_jet_bx_0_0x00f0 : jet_obj_t;
    signal comp_count_asymet_bx_0_0x0028 : asymet_obj_t;
    signal comp_count_asymet_bx_0_0x0032 : asymet_obj_t;
    signal comp_pt_etm_bx_0_0x00f0 : etm_obj_t;
    signal comp_pt_etmhf_bx_0_0x00f0 : etmhf_obj_t;
    signal comp_pt_htt_bx_0_0x0230 : htt_obj_t;
    signal comp_count_mbt0hfm_bx_0_0x0001 : mbt0hfm_obj_t;
    signal comp_count_mbt0hfp_bx_0_0x0001 : mbt0hfp_obj_t;
    signal comp_pt_mu_bx_0_0x0001 : mu_obj_t;
    signal comp_qual_mu_bx_0_0xff00 : mu_obj_t;
    signal comp_qual_mu_bx_0_0xfff0 : mu_obj_t;
    signal comp_pt_eg_bx_0_0x0018 : eg_obj_t;
    signal comp_pt_jet_bx_0_0x0038 : jet_obj_t;
    signal comp_eta_jet_bx_0_0x00c2_0x003d : jet_obj_t;
    signal comp_pt_eg_bx_0_0x001e : eg_obj_t;
    signal comp_pt_tau_bx_0_0x005a : tau_obj_t;
    signal comp_iso_tau_bx_0_0x000e : tau_obj_t;
    signal comp_pt_mu_bx_0_0x0007 : mu_obj_t;
    signal comp_qual_mu_bx_0_0xf000 : mu_obj_t;
-- Correlation cuts
    signal comp_dr_eg_jet_bx_0_bx_0_0x0000000027100_0x00000084ca240 : eg_jet_t;
    signal comp_deta_jet_jet_bx_0_bx_0_0x0000000000000_0x00000000005dc : jet_jet_t;
    signal comp_invmass_jet_jet_bx_0_bx_0_0x000010c388d00_0x41a6642c78140 : jet_jet_t;
    signal comp_invmass_jet_jet_bx_0_bx_0_0x00001448c1b40_0x41a6642c78140 : jet_jet_t;
    signal comp_invmass_jet_jet_bx_0_bx_0_0x000047999ed00_0x41a6642c78140 : jet_jet_t;
    signal comp_invmass_jet_jet_bx_0_bx_0_0x00000ba43b740_0x41a6642c78140 : jet_jet_t;
    signal comp_dr_jet_mu_bx_0_bx_0_0x0000000000000_0x00000000274e8 : jet_mu_t;
    signal comp_invmass_jet_jet_bx_0_bx_0_0x000025b7f3d40_0x41a6642c78140 : jet_jet_t;
    signal comp_dr_jet_tau_bx_0_bx_0_0x0000000000000_0x000000000a028 : jet_tau_t;
-- Muon charge correlation
    signal comp_cc_quad_bx_0_bx_0_cc_os : mu_cc_quad_t;
-- Conditions inputs
    -- Object cuts "and"
   signal comb_eg_bx_0_pt_000a_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : eg_obj_t;
   signal comb_jet_bx_0_pt_0096_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0082_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_00c8_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_003c_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_00dc_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0046_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_00be_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0096_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0082_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0028_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0078_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0028_eta_008d_00ba_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0028_eta_0045_0072_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0078_eta_008d_00ba_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_0078_eta_0045_0072_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_00f0_eta_008d_00ba_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_jet_bx_0_pt_00f0_eta_0045_0072_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_asymet_bx_0_count_0028 : asymet_obj_t;
   signal comb_asymet_bx_0_count_0032 : asymet_obj_t;
   signal comb_etm_bx_0_pt_00f0_phi_0000_0000_0000_0000 : etm_obj_t;
   signal comb_etmhf_bx_0_pt_00f0_phi_0000_0000_0000_0000 : etmhf_obj_t;
   signal comb_htt_bx_0_pt_0230_phi_0000_0000_0000_0000 : htt_obj_t;
   signal comb_mbt0hfm_bx_0_count_0001 : mbt0hfm_obj_t;
   signal comb_mbt0hfp_bx_0_count_0001 : mbt0hfp_obj_t;
   signal comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_ff00_charge_ign : mu_obj_t;
   signal comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_fff0_charge_ign : mu_obj_t;
   signal comb_eg_bx_0_pt_0018_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : eg_obj_t;
   signal comb_jet_bx_0_pt_0038_eta_00c2_003d_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_eg_bx_0_pt_001e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : eg_obj_t;
   signal comb_jet_bx_0_pt_003c_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_tau_bx_0_pt_005a_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000e : tau_obj_t;
   signal comb_jet_bx_0_pt_0046_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f : jet_obj_t;
   signal comb_mu_bx_0_pt_0007_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_f000_charge_ign : mu_obj_t;
-- Signal definition for conditions names
    signal single_asymet_i33 : std_logic;
    signal single_asymet_i34 : std_logic;
    signal single_cent0_i35 : std_logic;
    signal single_cent1_i36 : std_logic;
    signal single_cent2_i37 : std_logic;
    signal single_cent7_i38 : std_logic;
    signal single_ext_i25 : std_logic;
    signal single_ext_i26 : std_logic;
    signal single_mbt0_hfm_i32 : std_logic;
    signal single_mbt0_hfp_i31 : std_logic;
    signal single_etm_i23 : std_logic;
    signal single_etmhf_i24 : std_logic;
    signal single_htt_i22 : std_logic;
    signal calo_calo_correlation_i7 : std_logic;
    signal calo_calo_correlation_i8 : std_logic;
    signal calo_muon_correlation_i20 : std_logic;
    signal calo_muon_correlation_i21 : std_logic;
    signal invariant_mass_i10 : std_logic;
    signal invariant_mass_i11 : std_logic;
    signal invariant_mass_i28 : std_logic;
    signal invariant_mass_i30 : std_logic;
    signal invariant_mass_i9 : std_logic;
    signal invariant_mass_ov_rm_i19 : std_logic;
    signal double_eg_i2 : std_logic;
    signal double_jet_i13 : std_logic;
    signal double_jet_i27 : std_logic;
    signal double_jet_i29 : std_logic;
    signal double_mu_i0 : std_logic;
    signal quad_jet_i12 : std_logic;
    signal quad_jet_i16 : std_logic;
    signal quad_mu_i1 : std_logic;
    signal single_jet_i14 : std_logic;
    signal single_jet_i15 : std_logic;
    signal single_jet_i3 : std_logic;
    signal single_jet_i4 : std_logic;
    signal single_jet_i5 : std_logic;
    signal single_jet_i6 : std_logic;
    signal triple_jet_i17 : std_logic;
    signal triple_mu_i18 : std_logic;
-- Signal definition for algorithms names
    signal l1_quad_mu_open_os : std_logic;
    signal l1_double_mu0 : std_logic;
    signal l1_single_eg12_single_jet28_mid_eta2p7_min_dr0p4 : std_logic;
    signal l1_single_eg15_single_jet28_mid_eta2p7_min_dr0p4 : std_logic;
    signal l1_double_eg5 : std_logic;
    signal l1_single_jet60_fwd3p0 : std_logic;
    signal l1_single_jet120_fwd3p0 : std_logic;
    signal l1_double_jet30er2p5_mass_min250_d_eta_max1p5 : std_logic;
    signal l1_double_jet30er2p5_mass_min300_d_eta_max1p5 : std_logic;
    signal l1_double_jet30er2p5_mass_min330_d_eta_max1p5 : std_logic;
    signal l1_triple_mu0_oq : std_logic;
    signal l1_mu3_jet35er2p5_d_r_max0p4 : std_logic;
    signal l1_mu3_jet60er2p5_d_r_max0p4 : std_logic;
    signal l1_double_jet35_mass_min450_iso_tau45_rm_ovlp : std_logic;
    signal l1_triple_jet_95_75_65_double_jet_75_65_er2p5 : std_logic;
    signal l1_quad_jet_95_75_65_20_double_jet_75_65_er2p5_jet20_fwd3p0 : std_logic;
    signal l1_quad_jet60er2p5 : std_logic;
    signal l1_htt280er : std_logic;
    signal l1_etm120 : std_logic;
    signal l1_etmhf120 : std_logic;
    signal l1_unpaired_bunch_bptx_plus : std_logic;
    signal l1_unpaired_bunch_bptx_minus : std_logic;
    signal l1_double_jet_100_30_double_jet30_mass_min620 : std_logic;
    signal l1_double_jet_110_35_double_jet35_mass_min620 : std_logic;
    signal l1_minimum_bias_hf0_and_bptx_and : std_logic;
    signal l1_ett_asym40 : std_logic;
    signal l1_ett_asym50 : std_logic;
    signal l1_centrality_50_100 : std_logic;
    signal l1_centrality_saturation : std_logic;
begin
-- First stage: calculations
    calc_muon_charge_correlations_bx_0_bx_0_i: entity work.muon_charge_correlations
        port map(
            data.mu(bx(0)).charge,
            data.mu(bx(0)).charge,
            cc_double(bx(0),bx(0)),
            cc_triple(bx(0),bx(0)),
            cc_quad(bx(0),bx(0))
        );
  
    calc_deta_eg_jet_bx_0_bx_0_i: entity work.deta_calc
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS, (eg_t,jet_t)
        )
        port map(
            conv.eg(bx(0)).eta,
            conv.jet(bx(0)).eta,
            deta_calc_eg_jet(bx(0),bx(0))
        );
    calc_deta_lut_eg_jet_bx_0_bx_0_i: entity work.deta_lut
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS, (eg_t,jet_t)
        )
        port map(
            deta_calc_eg_jet(bx(0),bx(0)),
            deta_eg_jet(bx(0),bx(0))
        );
  
    calc_deta_jet_jet_bx_0_bx_0_i: entity work.deta_calc
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (jet_t,jet_t)
        )
        port map(
            conv.jet(bx(0)).eta,
            conv.jet(bx(0)).eta,
            deta_calc_jet_jet(bx(0),bx(0))
        );
    calc_deta_lut_jet_jet_bx_0_bx_0_i: entity work.deta_lut
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (jet_t,jet_t)
        )
        port map(
            deta_calc_jet_jet(bx(0),bx(0)),
            deta_jet_jet(bx(0),bx(0))
        );
  
    calc_deta_jet_tau_bx_0_bx_0_i: entity work.deta_calc
        generic map(
            N_JET_OBJECTS, N_TAU_OBJECTS, (jet_t,tau_t)
        )
        port map(
            conv.jet(bx(0)).eta,
            conv.tau(bx(0)).eta,
            deta_calc_jet_tau(bx(0),bx(0))
        );
    calc_deta_lut_jet_tau_bx_0_bx_0_i: entity work.deta_lut
        generic map(
            N_JET_OBJECTS, N_TAU_OBJECTS, (jet_t,tau_t)
        )
        port map(
            deta_calc_jet_tau(bx(0),bx(0)),
            deta_jet_tau(bx(0),bx(0))
        );
  
    calc_deta_jet_mu_bx_0_bx_0_i: entity work.deta_calc
        generic map(
            N_JET_OBJECTS, N_MU_OBJECTS, (jet_t,mu_t)
        )
        port map(    
            conv.jet(bx(0)).eta_conv_mu,
            conv.mu(bx(0)).eta,
            deta_calc_jet_mu(bx(0),bx(0))
        );
    calc_deta_lut_jet_mu_bx_0_bx_0_i: entity work.deta_lut
        generic map(
            N_JET_OBJECTS, N_MU_OBJECTS, (jet_t,mu_t)
        )
        port map(
            deta_calc_jet_mu(bx(0),bx(0)),
            deta_jet_mu(bx(0),bx(0))
        );
  
    calc_dphi_eg_jet_bx_0_bx_0_i: entity work.dphi_calc
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS, (eg_t,jet_t),
            EG_JET_PHI_HALF_RANGE_BINS
        )
        port map(
            conv.eg(bx(0)).phi,
            conv.jet(bx(0)).phi,
            dphi_calc_eg_jet(bx(0),bx(0))
        );
    calc_dphi_lut_eg_jet_bx_0_bx_0_i: entity work.dphi_lut
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS, (eg_t,jet_t)
        )
        port map(
            dphi_calc_eg_jet(bx(0),bx(0)),
            dphi_eg_jet(bx(0),bx(0))
        );
  
    calc_dphi_jet_jet_bx_0_bx_0_i: entity work.dphi_calc
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (jet_t,jet_t),
            JET_JET_PHI_HALF_RANGE_BINS
        )
        port map(
            conv.jet(bx(0)).phi,
            conv.jet(bx(0)).phi,
            dphi_calc_jet_jet(bx(0),bx(0))
        );
    calc_dphi_lut_jet_jet_bx_0_bx_0_i: entity work.dphi_lut
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (jet_t,jet_t)
        )
        port map(
            dphi_calc_jet_jet(bx(0),bx(0)),
            dphi_jet_jet(bx(0),bx(0))
        );
  
    calc_dphi_jet_tau_bx_0_bx_0_i: entity work.dphi_calc
        generic map(
            N_JET_OBJECTS, N_TAU_OBJECTS, (jet_t,tau_t),
            JET_TAU_PHI_HALF_RANGE_BINS
        )
        port map(
            conv.jet(bx(0)).phi,
            conv.tau(bx(0)).phi,
            dphi_calc_jet_tau(bx(0),bx(0))
        );
    calc_dphi_lut_jet_tau_bx_0_bx_0_i: entity work.dphi_lut
        generic map(
            N_JET_OBJECTS, N_TAU_OBJECTS, (jet_t,tau_t)
        )
        port map(
            dphi_calc_jet_tau(bx(0),bx(0)),
            dphi_jet_tau(bx(0),bx(0))
        );
  
    calc_dphi_jet_mu_bx_0_bx_0_i: entity work.dphi_calc
        generic map(
            N_JET_OBJECTS, N_MU_OBJECTS, (jet_t,mu_t),
            JET_MU_PHI_HALF_RANGE_BINS
        )
        port map(    
            conv.jet(bx(0)).phi_conv_mu,
            conv.mu(bx(0)).phi,
            dphi_calc_jet_mu(bx(0),bx(0))
        );
    calc_dphi_lut_jet_mu_bx_0_bx_0_i: entity work.dphi_lut
        generic map(
            N_JET_OBJECTS, N_MU_OBJECTS, (jet_t,mu_t)
        )
        port map(
            dphi_calc_jet_mu(bx(0),bx(0)),
            dphi_jet_mu(bx(0),bx(0))
        );
    calc_delta_r_eg_jet_bx_0_bx_0_i: entity work.delta_r
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS, (eg_t,jet_t)
        )
        port map(
            deta_eg_jet(bx(0),bx(0)),
            dphi_eg_jet(bx(0),bx(0)),
            dr_eg_jet(bx(0),bx(0))
        );
    calc_cosh_deta_jet_jet_bx_0_bx_0_i: entity work.cosh_deta_lut
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (JET_t,JET_t)
        )
        port map(
            deta_calc_jet_jet(bx(0),bx(0)),
            cosh_deta_jet_jet(bx(0),bx(0))
        );
    calc_cos_dphi_jet_jet_bx_0_bx_0_i: entity work.cos_dphi_lut
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (JET_t,JET_t)
        )
        port map(
            dphi_calc_jet_jet(bx(0),bx(0)),
            cos_dphi_jet_jet(bx(0),bx(0))
        );
    calc_inv_mass_jet_jet_bx_0_bx_0_i: entity work.invariant_mass
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (jet_t,jet_t),
            JET_PT_VECTOR_WIDTH, JET_PT_VECTOR_WIDTH,
            JET_JET_COSH_COS_VECTOR_WIDTH
        )
        port map(
            conv.jet(bx(0)).pt_vector,
            conv.jet(bx(0)).pt_vector,
            cosh_deta_jet_jet(bx(0),bx(0)),
            cos_dphi_jet_jet(bx(0),bx(0)),
            invmass_jet_jet(bx(0),bx(0))
       );
    calc_delta_r_jet_mu_bx_0_bx_0_i: entity work.delta_r
        generic map(
            N_JET_OBJECTS, N_MU_OBJECTS, (jet_t,mu_t)
        )
        port map(
            deta_jet_mu(bx(0),bx(0)),
            dphi_jet_mu(bx(0),bx(0)),
            dr_jet_mu(bx(0),bx(0))
        );
    calc_delta_r_jet_tau_bx_0_bx_0_i: entity work.delta_r
        generic map(
            N_JET_OBJECTS, N_TAU_OBJECTS, (jet_t,tau_t)
        )
        port map(
            deta_jet_tau(bx(0),bx(0)),
            dphi_jet_tau(bx(0),bx(0)),
            dr_jet_tau(bx(0),bx(0))
        );
    
-- Second stage: comparisons
    comp_pt_eg_bx_0_0x000a_i: entity work.comparators_obj_cuts
        generic map(
            N_EG_OBJECTS, EG_PT_WIDTH,  
            GE,  
            X"000a", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.eg(bx(0)).pt, comp_pt_eg_bx_0_0x000a
        );
    comp_pt_jet_bx_0_0x0096_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0096", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0096
        );
    comp_eta_jet_bx_0_0x00c6_0x0039_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_ETA_WIDTH,
            ETA, X"00C6", X"0039", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).eta, comp_eta_jet_bx_0_0x00c6_0x0039
        );
    comp_pt_jet_bx_0_0x0082_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0082", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0082
        );
    comp_pt_jet_bx_0_0x00c8_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"00c8", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x00c8
        );
    comp_pt_jet_bx_0_0x003c_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"003c", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x003c
        );
    comp_pt_jet_bx_0_0x00dc_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"00dc", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x00dc
        );
    comp_pt_jet_bx_0_0x0046_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0046", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0046
        );
    comp_pt_jet_bx_0_0x00be_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"00be", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x00be
        );
    comp_pt_jet_bx_0_0x0028_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0028", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0028
        );
    comp_pt_jet_bx_0_0x0078_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0078", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0078
        );
    comp_eta_jet_bx_0_0x008d_0x00ba_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_ETA_WIDTH,
            ETA, X"008D", X"00BA", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).eta, comp_eta_jet_bx_0_0x008d_0x00ba
        );
    comp_eta_jet_bx_0_0x0045_0x0072_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_ETA_WIDTH,
            ETA, X"0045", X"0072", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).eta, comp_eta_jet_bx_0_0x0045_0x0072
        );
    comp_pt_jet_bx_0_0x00f0_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"00f0", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x00f0
        );
    comp_count_asymet_bx_0_0x0028_i: entity work.comparators_obj_cuts
        generic map(
            N_ASYMET_OBJECTS, ASYMET_WIDTH,
            GE, X"0028", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.asymet(bx(0)).count, comp_count_asymet_bx_0_0x0028
        );
    comp_count_asymet_bx_0_0x0032_i: entity work.comparators_obj_cuts
        generic map(
            N_ASYMET_OBJECTS, ASYMET_WIDTH,
            GE, X"0032", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.asymet(bx(0)).count, comp_count_asymet_bx_0_0x0032
        );
    comp_pt_etm_bx_0_0x00f0_i: entity work.comparators_obj_cuts
        generic map(
            N_ETM_OBJECTS, ETM_PT_WIDTH,  
            GE,  
            X"00f0", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.etm(bx(0)).pt, comp_pt_etm_bx_0_0x00f0
        );
    comp_pt_etmhf_bx_0_0x00f0_i: entity work.comparators_obj_cuts
        generic map(
            N_ETMHF_OBJECTS, ETMHF_PT_WIDTH,  
            GE,  
            X"00f0", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.etmhf(bx(0)).pt, comp_pt_etmhf_bx_0_0x00f0
        );
    comp_pt_htt_bx_0_0x0230_i: entity work.comparators_obj_cuts
        generic map(
            N_HTT_OBJECTS, HTT_PT_WIDTH,  
            GE,  
            X"0230", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.htt(bx(0)).pt, comp_pt_htt_bx_0_0x0230
        );
    comp_count_mbt0hfm_bx_0_0x0001_i: entity work.comparators_obj_cuts
        generic map(
            N_MBT0HFM_OBJECTS, MBT0HFM_WIDTH,
            GE, X"0001", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.mbt0hfm(bx(0)).count, comp_count_mbt0hfm_bx_0_0x0001
        );
    comp_count_mbt0hfp_bx_0_0x0001_i: entity work.comparators_obj_cuts
        generic map(
            N_MBT0HFP_OBJECTS, MBT0HFP_WIDTH,
            GE, X"0001", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.mbt0hfp(bx(0)).count, comp_count_mbt0hfp_bx_0_0x0001
        );
    comp_pt_mu_bx_0_0x0001_i: entity work.comparators_obj_cuts
        generic map(
            N_MU_OBJECTS, MU_PT_WIDTH,  
            GE,  
            X"0001", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.mu(bx(0)).pt, comp_pt_mu_bx_0_0x0001
        );
    comp_qual_mu_bx_0_0xff00_i: entity work.comparators_obj_cuts
        generic map(
            N_MU_OBJECTS, MU_QUAL_WIDTH,
            QUAL, X"0000", X"0000", X"FF00", "ign"
        )
        port map(
            lhc_clk, data.mu(bx(0)).qual, comp_qual_mu_bx_0_0xff00
        );
    comp_qual_mu_bx_0_0xfff0_i: entity work.comparators_obj_cuts
        generic map(
            N_MU_OBJECTS, MU_QUAL_WIDTH,
            QUAL, X"0000", X"0000", X"FFF0", "ign"
        )
        port map(
            lhc_clk, data.mu(bx(0)).qual, comp_qual_mu_bx_0_0xfff0
        );
    comp_pt_eg_bx_0_0x0018_i: entity work.comparators_obj_cuts
        generic map(
            N_EG_OBJECTS, EG_PT_WIDTH,  
            GE,  
            X"0018", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.eg(bx(0)).pt, comp_pt_eg_bx_0_0x0018
        );
    comp_pt_jet_bx_0_0x0038_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_PT_WIDTH,  
            GE,  
            X"0038", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).pt, comp_pt_jet_bx_0_0x0038
        );
    comp_eta_jet_bx_0_0x00c2_0x003d_i: entity work.comparators_obj_cuts
        generic map(
            N_JET_OBJECTS, JET_ETA_WIDTH,
            ETA, X"00C2", X"003D", X"0000", "ign"
        )
        port map(
            lhc_clk, data.jet(bx(0)).eta, comp_eta_jet_bx_0_0x00c2_0x003d
        );
    comp_pt_eg_bx_0_0x001e_i: entity work.comparators_obj_cuts
        generic map(
            N_EG_OBJECTS, EG_PT_WIDTH,  
            GE,  
            X"001e", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.eg(bx(0)).pt, comp_pt_eg_bx_0_0x001e
        );
    comp_pt_tau_bx_0_0x005a_i: entity work.comparators_obj_cuts
        generic map(
            N_TAU_OBJECTS, TAU_PT_WIDTH,  
            GE,  
            X"005a", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.tau(bx(0)).pt, comp_pt_tau_bx_0_0x005a
        );
    comp_iso_tau_bx_0_0x000e_i: entity work.comparators_obj_cuts
        generic map(
            N_TAU_OBJECTS, TAU_ISO_WIDTH,
            ISO, X"0000", X"0000", X"000E", "ign"
        )
        port map(
            lhc_clk, data.tau(bx(0)).iso, comp_iso_tau_bx_0_0x000e
        );
    comp_pt_mu_bx_0_0x0007_i: entity work.comparators_obj_cuts
        generic map(
            N_MU_OBJECTS, MU_PT_WIDTH,  
            GE,  
            X"0007", X"0000", X"0000", "ign"
        )
        port map(
            lhc_clk, data.mu(bx(0)).pt, comp_pt_mu_bx_0_0x0007
        );
    comp_qual_mu_bx_0_0xf000_i: entity work.comparators_obj_cuts
        generic map(
            N_MU_OBJECTS, MU_QUAL_WIDTH,
            QUAL, X"0000", X"0000", X"F000", "ign"
        )
        port map(
            lhc_clk, data.mu(bx(0)).qual, comp_qual_mu_bx_0_0xf000
        );
    comp_dr_eg_jet_bx_0_bx_0_0x0000000027100_0x00000084ca240_i: entity work.comparators_corr_cuts
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS, (eg_t,jet_t),
            EG_JET_DELTAR_VECTOR_WIDTH, deltaR, 
            X"0000000027100", X"00000084CA240"        
        )
        port map(
            lhc_clk, 
            dr_eg_jet(bx(0),bx(0)), comp_dr_eg_jet_bx_0_bx_0_0x0000000027100_0x00000084ca240
        );
    comp_deta_jet_jet_bx_0_bx_0_0x0000000000000_0x00000000005dc_i: entity work.comparators_corr_cuts
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (jet_t,jet_t),
            JET_JET_DELTAETA_VECTOR_WIDTH, deltaEta, 
            X"0000000000000", X"00000000005DC"        
        )
        port map(
            lhc_clk, 
            deta_jet_jet(bx(0),bx(0)), comp_deta_jet_jet_bx_0_bx_0_0x0000000000000_0x00000000005dc
        );
    comp_invmass_jet_jet_bx_0_bx_0_0x000010c388d00_0x41a6642c78140_i: entity work.comparators_corr_cuts
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (jet_t,jet_t),
            JET_JET_MASS_VECTOR_WIDTH, mass, 
            X"000010C388D00", X"41A6642C78140"        
        )
        port map(
            lhc_clk, 
            invmass_jet_jet(bx(0),bx(0)), comp_invmass_jet_jet_bx_0_bx_0_0x000010c388d00_0x41A6642C78140
        );
    comp_invmass_jet_jet_bx_0_bx_0_0x00001448c1b40_0x41a6642c78140_i: entity work.comparators_corr_cuts
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (jet_t,jet_t),
            JET_JET_MASS_VECTOR_WIDTH, mass, 
            X"00001448C1B40", X"41A6642C78140"        
        )
        port map(
            lhc_clk, 
            invmass_jet_jet(bx(0),bx(0)), comp_invmass_jet_jet_bx_0_bx_0_0x00001448c1b40_0x41A6642C78140
        );
    comp_invmass_jet_jet_bx_0_bx_0_0x000047999ed00_0x41a6642c78140_i: entity work.comparators_corr_cuts
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (jet_t,jet_t),
            JET_JET_MASS_VECTOR_WIDTH, mass, 
            X"000047999ED00", X"41A6642C78140"        
        )
        port map(
            lhc_clk, 
            invmass_jet_jet(bx(0),bx(0)), comp_invmass_jet_jet_bx_0_bx_0_0x000047999ed00_0x41A6642C78140
        );
    comp_invmass_jet_jet_bx_0_bx_0_0x00000ba43b740_0x41a6642c78140_i: entity work.comparators_corr_cuts
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (jet_t,jet_t),
            JET_JET_MASS_VECTOR_WIDTH, mass, 
            X"00000BA43B740", X"41A6642C78140"        
        )
        port map(
            lhc_clk, 
            invmass_jet_jet(bx(0),bx(0)), comp_invmass_jet_jet_bx_0_bx_0_0x00000ba43b740_0x41A6642C78140
        );
    comp_dr_jet_mu_bx_0_bx_0_0x0000000000000_0x00000000274e8_i: entity work.comparators_corr_cuts
        generic map(
            N_JET_OBJECTS, N_MU_OBJECTS, (jet_t,mu_t),
            JET_MU_DELTAR_VECTOR_WIDTH, deltaR, 
            X"0000000000000", X"00000000274E8"        
        )
        port map(
            lhc_clk, 
            dr_jet_mu(bx(0),bx(0)), comp_dr_jet_mu_bx_0_bx_0_0x0000000000000_0x00000000274e8
        );
    comp_invmass_jet_jet_bx_0_bx_0_0x000025b7f3d40_0x41a6642c78140_i: entity work.comparators_corr_cuts
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS, (jet_t,jet_t),
            JET_JET_MASS_VECTOR_WIDTH, mass, 
            X"000025B7F3D40", X"41A6642C78140"        
        )
        port map(
            lhc_clk, 
            invmass_jet_jet(bx(0),bx(0)), comp_invmass_jet_jet_bx_0_bx_0_0x000025b7f3d40_0x41A6642C78140
        );
    comp_dr_jet_tau_bx_0_bx_0_0x0000000000000_0x000000000a028_i: entity work.comparators_corr_cuts
        generic map(
            N_JET_OBJECTS, N_TAU_OBJECTS, (jet_t,tau_t),
            JET_TAU_DELTAR_VECTOR_WIDTH, deltaR, 
            X"0000000000000", X"000000000A028"        
        )
        port map(
            lhc_clk, 
            dr_jet_tau(bx(0),bx(0)), comp_dr_jet_tau_bx_0_bx_0_0x0000000000000_0x000000000a028
        );
    comp_cc_quad_bx_0_bx_0_cc_os_i: entity work.comparators_muon_charge_corr
        generic map(
            quad, CC_OS
        )
        port map(
            lhc_clk, 
            cc_quad => cc_quad(bx(0),bx(0)), 
            comp_o_quad => comp_cc_quad_bx_0_bx_0_cc_os
        );

-- Third stage: conditions and algos
    -- Creating condition inputs (combination of object cuts)
    comb_eg_bx_0_pt_000a_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_eg_bx_0_0x000a
    ;

    comb_jet_bx_0_pt_0096_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0096
    and comp_eta_jet_bx_0_0x00c6_0x0039
    ;

    comb_jet_bx_0_pt_0082_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0082
    and comp_eta_jet_bx_0_0x00c6_0x0039
    ;

    comb_jet_bx_0_pt_00c8_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x00c8
    ;

    comb_jet_bx_0_pt_003c_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x003c
    ;

    comb_jet_bx_0_pt_00dc_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x00dc
    ;

    comb_jet_bx_0_pt_0046_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0046
    ;

    comb_jet_bx_0_pt_00be_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x00be
    ;

    comb_jet_bx_0_pt_0096_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0096
    ;

    comb_jet_bx_0_pt_0082_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0082
    ;

    comb_jet_bx_0_pt_0028_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0028
    ;

    comb_jet_bx_0_pt_0078_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0078
    and comp_eta_jet_bx_0_0x00c6_0x0039
    ;

    comb_jet_bx_0_pt_0028_eta_008d_00ba_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0028
    and comp_eta_jet_bx_0_0x008d_0x00ba
    ;

    comb_jet_bx_0_pt_0028_eta_0045_0072_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0028
    and comp_eta_jet_bx_0_0x0045_0x0072
    ;

    comb_jet_bx_0_pt_0078_eta_008d_00ba_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0078
    and comp_eta_jet_bx_0_0x008d_0x00ba
    ;

    comb_jet_bx_0_pt_0078_eta_0045_0072_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0078
    and comp_eta_jet_bx_0_0x0045_0x0072
    ;

    comb_jet_bx_0_pt_00f0_eta_008d_00ba_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x00f0
    and comp_eta_jet_bx_0_0x008d_0x00ba
    ;

    comb_jet_bx_0_pt_00f0_eta_0045_0072_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x00f0
    and comp_eta_jet_bx_0_0x0045_0x0072
    ;

    comb_asymet_bx_0_count_0028 <= 
    comp_count_asymet_bx_0_0x0028;

    comb_asymet_bx_0_count_0032 <= 
    comp_count_asymet_bx_0_0x0032;

    comb_etm_bx_0_pt_00f0_phi_0000_0000_0000_0000 <= 
    comp_pt_etm_bx_0_0x00f0
    ;

    comb_etmhf_bx_0_pt_00f0_phi_0000_0000_0000_0000 <= 
    comp_pt_etmhf_bx_0_0x00f0
    ;

    comb_htt_bx_0_pt_0230_phi_0000_0000_0000_0000 <= 
    comp_pt_htt_bx_0_0x0230
    ;

    comb_mbt0hfm_bx_0_count_0001 <= 
    comp_count_mbt0hfm_bx_0_0x0001;

    comb_mbt0hfp_bx_0_count_0001 <= 
    comp_count_mbt0hfp_bx_0_0x0001;

    comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_ff00_charge_ign <= 
    comp_pt_mu_bx_0_0x0001
    and comp_qual_mu_bx_0_0xff00
    ;

    comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_fff0_charge_ign <= 
    comp_pt_mu_bx_0_0x0001
    and comp_qual_mu_bx_0_0xfff0
    ;

    comb_eg_bx_0_pt_0018_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_eg_bx_0_0x0018
    ;

    comb_jet_bx_0_pt_0038_eta_00c2_003d_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0038
    and comp_eta_jet_bx_0_0x00c2_0x003d
    ;

    comb_eg_bx_0_pt_001e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_eg_bx_0_0x001e
    ;

    comb_jet_bx_0_pt_003c_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x003c
    and comp_eta_jet_bx_0_0x00c6_0x0039
    ;

    comb_tau_bx_0_pt_005a_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000e <= 
    comp_pt_tau_bx_0_0x005a
    and comp_iso_tau_bx_0_0x000e
    ;

    comb_jet_bx_0_pt_0046_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f <= 
    comp_pt_jet_bx_0_0x0046
    and comp_eta_jet_bx_0_0x00c6_0x0039
    ;

    comb_mu_bx_0_pt_0007_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_f000_charge_ign <= 
    comp_pt_mu_bx_0_0x0007
    and comp_qual_mu_bx_0_0xf000
    ;

    -- Instantiations of conditions
    cond_double_eg_i2_i: entity work.combinatorial_conditions
        generic map(
            N_EG_OBJECTS, 2,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_eg_bx_0_pt_000a_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_eg_bx_0_pt_000a_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => double_eg_i2
        );
    cond_double_jet_i13_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 2,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_0096_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_0082_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => double_jet_i13
        );
    cond_double_jet_i27_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 2,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_00c8_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_003c_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => double_jet_i27
        );
    cond_double_jet_i29_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 2,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_00dc_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_0046_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => double_jet_i29
        );
    cond_quad_jet_i12_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 4,
            ((0,11), (0,11), (0,11), (0,11)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_00be_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_0096_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_0_pt_0082_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_jet_bx_0_pt_0028_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => quad_jet_i12
        );
    cond_quad_jet_i16_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 4,
            ((0,11), (0,11), (0,11), (0,11)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_0078_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_0078_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_0_pt_0078_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_4 =>
            comb_jet_bx_0_pt_0078_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => quad_jet_i16
        );
    cond_single_jet_i14_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 1,
            ((0,11), (0,0), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_0028_eta_008d_00ba_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => single_jet_i14
        );
    cond_single_jet_i15_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 1,
            ((0,11), (0,0), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_0028_eta_0045_0072_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => single_jet_i15
        );
    cond_single_jet_i3_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 1,
            ((0,11), (0,0), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_0078_eta_008d_00ba_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => single_jet_i3
        );
    cond_single_jet_i4_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 1,
            ((0,11), (0,0), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_0078_eta_0045_0072_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => single_jet_i4
        );
    cond_single_jet_i5_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 1,
            ((0,11), (0,0), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_00f0_eta_008d_00ba_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => single_jet_i5
        );
    cond_single_jet_i6_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 1,
            ((0,11), (0,0), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_00f0_eta_0045_0072_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => single_jet_i6
        );
    cond_triple_jet_i17_i: entity work.combinatorial_conditions
        generic map(
            N_JET_OBJECTS, 3,
            ((0,11), (0,11), (0,11), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_jet_bx_0_pt_00be_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_2 =>
            comb_jet_bx_0_pt_0096_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            comb_3 =>
            comb_jet_bx_0_pt_0082_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            cond_o => triple_jet_i17
        );
    cond_single_asymet_i33_i: entity work.combinatorial_conditions
        generic map(
            N_ASYMET_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_asymet_bx_0_count_0028,
            cond_o => single_asymet_i33
        );
    cond_single_asymet_i34_i: entity work.combinatorial_conditions
        generic map(
            N_ASYMET_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_asymet_bx_0_count_0032,
            cond_o => single_asymet_i34
        );
    cond_single_etm_i23_i: entity work.combinatorial_conditions
        generic map(
            N_ETM_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_etm_bx_0_pt_00f0_phi_0000_0000_0000_0000,
            cond_o => single_etm_i23
        );
    cond_single_etmhf_i24_i: entity work.combinatorial_conditions
        generic map(
            N_ETMHF_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_etmhf_bx_0_pt_00f0_phi_0000_0000_0000_0000,
            cond_o => single_etmhf_i24
        );
    cond_single_htt_i22_i: entity work.combinatorial_conditions
        generic map(
            N_HTT_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_htt_bx_0_pt_0230_phi_0000_0000_0000_0000,
            cond_o => single_htt_i22
        );
    cond_single_mbt0_hfm_i32_i: entity work.combinatorial_conditions
        generic map(
            N_MBT0HFM_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_mbt0hfm_bx_0_count_0001,
            cond_o => single_mbt0_hfm_i32
        );
    cond_single_mbt0_hfp_i31_i: entity work.combinatorial_conditions
        generic map(
            N_MBT0HFP_OBJECTS, 1,
            ((0,0), (0,0), (0,0), (0,0)), 
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_mbt0hfp_bx_0_count_0001,
            cond_o => single_mbt0_hfp_i31
        );
    cond_double_mu_i0_i: entity work.combinatorial_conditions
        generic map(
            N_MU_OBJECTS, 2,
            ((0,7), (0,7), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_ff00_charge_ign,
            comb_2 =>
            comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_ff00_charge_ign,
            cond_o => double_mu_i0
        );
    cond_quad_mu_i1_i: entity work.combinatorial_conditions
        generic map(
            N_MU_OBJECTS, 4,
            ((0,7), (0,7), (0,7), (0,7)),
            true
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_fff0_charge_ign,
            comb_2 =>
            comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_fff0_charge_ign,
            comb_3 =>
            comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_fff0_charge_ign,
            comb_4 =>
            comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_fff0_charge_ign,
            charge_corr_quad => comp_cc_quad_bx_0_bx_0_cc_os,
            cond_o => quad_mu_i1
        );
    cond_triple_mu_i18_i: entity work.combinatorial_conditions
        generic map(
            N_MU_OBJECTS, 3,
            ((0,7), (0,7), (0,7), (0,0)),
            false
        )
        port map(
            lhc_clk,
            comb_1 =>
            comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_fff0_charge_ign,
            comb_2 =>
            comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_fff0_charge_ign,
            comb_3 =>
            comb_mu_bx_0_pt_0001_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_fff0_charge_ign,
            cond_o => triple_mu_i18
        );
    cond_calo_calo_correlation_i7_i: entity work.correlation_conditions
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            in_1 => 
            comb_eg_bx_0_pt_0018_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            in_2 => 
            comb_jet_bx_0_pt_0038_eta_00c2_003d_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f, 
            delta_r => comp_dr_eg_jet_bx_0_bx_0_0x0000000027100_0x00000084ca240,
            cond_o => calo_calo_correlation_i7
        );

    cond_calo_calo_correlation_i8_i: entity work.correlation_conditions
        generic map(
            N_EG_OBJECTS, N_JET_OBJECTS,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            in_1 => 
            comb_eg_bx_0_pt_001e_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            in_2 => 
            comb_jet_bx_0_pt_0038_eta_00c2_003d_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f, 
            delta_r => comp_dr_eg_jet_bx_0_bx_0_0x0000000027100_0x00000084ca240,
            cond_o => calo_calo_correlation_i8
        );

    cond_invariant_mass_i10_i: entity work.correlation_conditions
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            in_1 => 
            comb_jet_bx_0_pt_003c_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            in_2 => 
            comb_jet_bx_0_pt_003c_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f, 
            deta => comp_deta_jet_jet_bx_0_bx_0_0x0000000000000_0x00000000005dc, 
            inv_mass => comp_invmass_jet_jet_bx_0_bx_0_0x000010c388d00_0x41a6642c78140,
            cond_o => invariant_mass_i10
        );

    cond_invariant_mass_i11_i: entity work.correlation_conditions
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            in_1 => 
            comb_jet_bx_0_pt_003c_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            in_2 => 
            comb_jet_bx_0_pt_003c_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f, 
            deta => comp_deta_jet_jet_bx_0_bx_0_0x0000000000000_0x00000000005dc, 
            inv_mass => comp_invmass_jet_jet_bx_0_bx_0_0x00001448c1b40_0x41a6642c78140,
            cond_o => invariant_mass_i11
        );

    cond_invariant_mass_i28_i: entity work.correlation_conditions
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            in_1 => 
            comb_jet_bx_0_pt_003c_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            in_2 => 
            comb_jet_bx_0_pt_003c_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f, 
            inv_mass => comp_invmass_jet_jet_bx_0_bx_0_0x000047999ed00_0x41a6642c78140,
            cond_o => invariant_mass_i28
        );

    cond_invariant_mass_i30_i: entity work.correlation_conditions
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            in_1 => 
            comb_jet_bx_0_pt_0046_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            in_2 => 
            comb_jet_bx_0_pt_0046_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f, 
            inv_mass => comp_invmass_jet_jet_bx_0_bx_0_0x000047999ed00_0x41a6642c78140,
            cond_o => invariant_mass_i30
        );

    cond_invariant_mass_i9_i: entity work.correlation_conditions
        generic map(
            N_JET_OBJECTS, N_JET_OBJECTS,
            ((0,11), (0,11), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            in_1 => 
            comb_jet_bx_0_pt_003c_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            in_2 => 
            comb_jet_bx_0_pt_003c_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f, 
            deta => comp_deta_jet_jet_bx_0_bx_0_0x0000000000000_0x00000000005dc, 
            inv_mass => comp_invmass_jet_jet_bx_0_bx_0_0x00000ba43b740_0x41a6642c78140,
            cond_o => invariant_mass_i9
        );

    cond_calo_muon_correlation_i20_i: entity work.correlation_conditions
        generic map(
            N_JET_OBJECTS, N_MU_OBJECTS,
            ((0,11), (0,7), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            in_1 => 
            comb_jet_bx_0_pt_0046_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            in_2 => 
            comb_mu_bx_0_pt_0007_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_f000_charge_ign, 
            delta_r => comp_dr_jet_mu_bx_0_bx_0_0x0000000000000_0x00000000274e8,
            cond_o => calo_muon_correlation_i20
        );

    cond_calo_muon_correlation_i21_i: entity work.correlation_conditions
        generic map(
            N_JET_OBJECTS, N_MU_OBJECTS,
            ((0,11), (0,7), (0,0), (0,0)),
            false
        )
        port map(
            lhc_clk,
            in_1 => 
            comb_jet_bx_0_pt_0078_eta_00c6_0039_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            in_2 => 
            comb_mu_bx_0_pt_0007_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f_qual_f000_charge_ign, 
            delta_r => comp_dr_jet_mu_bx_0_bx_0_0x0000000000000_0x00000000274e8,
            cond_o => calo_muon_correlation_i21
        );

    cond_invariant_mass_ov_rm_i19_i: entity work.correlation_conditions_ovrm
        generic map(  
            N_JET_OBJECTS, N_JET_OBJECTS,  N_TAU_OBJECTS,
            ((0,11), (0,11), (0,11), (0,0)),
            false,  
            true
        )
        port map(
            lhc_clk,
            in_1 => 
            comb_jet_bx_0_pt_0046_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            in_2 => 
            comb_jet_bx_0_pt_0046_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000f,
            in_3 => 
            comb_tau_bx_0_pt_005a_eta_0000_0000_0000_0000_0000_0000_0000_0000_0000_0000_phi_0000_0000_0000_0000_iso_000e, 
            inv_mass => comp_invmass_jet_jet_bx_0_bx_0_0x000025b7f3d40_0x41a6642c78140, 
            dr_ovrm => comp_dr_jet_tau_bx_0_bx_0_0x0000000000000_0x000000000a028,
            cond_o => invariant_mass_ov_rm_i19
        );    
    -- Centrality assignment  
    single_cent0_i35 <= data.centrality(bx(0))(0);  
    single_cent1_i36 <= data.centrality(bx(0))(1);  
    single_cent2_i37 <= data.centrality(bx(0))(2);  
    single_cent7_i38 <= data.centrality(bx(0))(7);
    -- External condition assignment
    single_ext_i25 <= data.ext_cond(bx(0))(9);
    single_ext_i26 <= data.ext_cond(bx(0))(10);
    -- Instantiations of algorithms

-- 0 L1_QuadMuOpen_OS : comb{MU0[MU-QLTY_OPEN],MU0[MU-QLTY_OPEN],MU0[MU-QLTY_OPEN],MU0[MU-QLTY_OPEN]}[CHGCOR_OS]
    l1_quad_mu_open_os <= quad_mu_i1;
    algo(17) <= l1_quad_mu_open_os;
-- 1 L1_DoubleMu0 : comb{MU0[MU-QLTY_DBLE],MU0[MU-QLTY_DBLE]}
    l1_double_mu0 <= double_mu_i0;
    algo(15) <= l1_double_mu0;
-- 2 L1_SingleEG12_SingleJet28_MidEta2p7_MinDr0p4 : dist{EG12,JET28[JET-ETA_2p7]}[DR_MIN_0p4]
    l1_single_eg12_single_jet28_mid_eta2p7_min_dr0p4 <= calo_calo_correlation_i7;
    algo(24) <= l1_single_eg12_single_jet28_mid_eta2p7_min_dr0p4;
-- 3 L1_SingleEG15_SingleJet28_MidEta2p7_MinDr0p4 : dist{EG15,JET28[JET-ETA_2p7]}[DR_MIN_0p4]
    l1_single_eg15_single_jet28_mid_eta2p7_min_dr0p4 <= calo_calo_correlation_i8;
    algo(25) <= l1_single_eg15_single_jet28_mid_eta2p7_min_dr0p4;
-- 4 L1_DoubleEG5 : comb{EG5,EG5}
    l1_double_eg5 <= double_eg_i2;
    algo(10) <= l1_double_eg5;
-- 5 L1_SingleJet60_FWD3p0 : JET60[JET-ETA_FWD_3p00_NEG] OR JET60[JET-ETA_FWD_3p00_POS]
    l1_single_jet60_fwd3p0 <= single_jet_i3 or single_jet_i4;
    algo(12) <= l1_single_jet60_fwd3p0;
-- 6 L1_SingleJet120_FWD3p0 : JET120[JET-ETA_FWD_3p00_NEG] OR JET120[JET-ETA_FWD_3p00_POS]
    l1_single_jet120_fwd3p0 <= single_jet_i5 or single_jet_i6;
    algo(11) <= l1_single_jet120_fwd3p0;
-- 7 L1_DoubleJet30er2p5_Mass_Min250_dEta_Max1p5 : mass_inv{JET30[JET-ETA_2p52],JET30[JET-ETA_2p52]}[MASS_MIN_250,DETA_MAX_1p5]
    l1_double_jet30er2p5_mass_min250_d_eta_max1p5 <= invariant_mass_i9;
    algo(21) <= l1_double_jet30er2p5_mass_min250_d_eta_max1p5;
-- 8 L1_DoubleJet30er2p5_Mass_Min300_dEta_Max1p5 : mass_inv{JET30[JET-ETA_2p52],JET30[JET-ETA_2p52]}[MASS_MIN_300,DETA_MAX_1p5]
    l1_double_jet30er2p5_mass_min300_d_eta_max1p5 <= invariant_mass_i10;
    algo(22) <= l1_double_jet30er2p5_mass_min300_d_eta_max1p5;
-- 9 L1_DoubleJet30er2p5_Mass_Min330_dEta_Max1p5 : mass_inv{JET30[JET-ETA_2p52],JET30[JET-ETA_2p52]}[MASS_MIN_330,DETA_MAX_1p5]
    l1_double_jet30er2p5_mass_min330_d_eta_max1p5 <= invariant_mass_i11;
    algo(23) <= l1_double_jet30er2p5_mass_min330_d_eta_max1p5;
-- 10 L1_TripleMu0_OQ : comb{MU0[MU-QLTY_OPEN],MU0[MU-QLTY_OPEN],MU0[MU-QLTY_OPEN]}
    l1_triple_mu0_oq <= triple_mu_i18;
    algo(16) <= l1_triple_mu0_oq;
-- 11 L1_Mu3_Jet35er2p5_dR_Max0p4 : dist{MU3[MU-QLTY_SNGL],JET35[JET-ETA_2p52]}[DR_MAX_0p4]
    l1_mu3_jet35er2p5_d_r_max0p4 <= calo_muon_correlation_i20;
    algo(26) <= l1_mu3_jet35er2p5_d_r_max0p4;
-- 12 L1_Mu3_Jet60er2p5_dR_Max0p4 : dist{MU3[MU-QLTY_SNGL],JET60[JET-ETA_2p52]}[DR_MAX_0p4]
    l1_mu3_jet60er2p5_d_r_max0p4 <= calo_muon_correlation_i21;
    algo(27) <= l1_mu3_jet60er2p5_d_r_max0p4;
-- 13 L1_DoubleJet35_Mass_Min450_IsoTau45_RmOvlp : mass_inv_orm{JET35,JET35,TAU45[TAU-ISO_0xE]}[MASS_MIN_450,ORMDR_0p2]
    l1_double_jet35_mass_min450_iso_tau45_rm_ovlp <= invariant_mass_ov_rm_i19;
    algo(28) <= l1_double_jet35_mass_min450_iso_tau45_rm_ovlp;
-- 14 L1_TripleJet_95_75_65_DoubleJet_75_65_er2p5 : comb{JET95,JET75,JET65} AND comb{JET75[JET-ETA_2p52],JET65[JET-ETA_2p52]}
    l1_triple_jet_95_75_65_double_jet_75_65_er2p5 <= triple_jet_i17 and double_jet_i13;
    algo(13) <= l1_triple_jet_95_75_65_double_jet_75_65_er2p5;
-- 15 L1_QuadJet_95_75_65_20_DoubleJet_75_65_er2p5_Jet20_FWD3p0 : comb{JET95,JET75,JET65,JET20} AND comb{JET75[JET-ETA_2p52],JET65[JET-ETA_2p52]} AND (JET20[JET-ETA_FWD_3p00_NEG] OR JET20[JET-ETA_FWD_3p00_POS])
    l1_quad_jet_95_75_65_20_double_jet_75_65_er2p5_jet20_fwd3p0 <= quad_jet_i12 and double_jet_i13 and ( single_jet_i14 or single_jet_i15 );
    algo(14) <= l1_quad_jet_95_75_65_20_double_jet_75_65_er2p5_jet20_fwd3p0;
-- 16 L1_QuadJet60er2p5 : comb{JET60[JET-ETA_2p52],JET60[JET-ETA_2p52],JET60[JET-ETA_2p52],JET60[JET-ETA_2p52]}
    l1_quad_jet60er2p5 <= quad_jet_i16;
    algo(18) <= l1_quad_jet60er2p5;
-- 17 L1_HTT280er : HTT280
    l1_htt280er <= single_htt_i22;
    algo(8) <= l1_htt280er;
-- 18 L1_ETM120 : ETM120
    l1_etm120 <= single_etm_i23;
    algo(4) <= l1_etm120;
-- 19 L1_ETMHF120 : ETMHF120
    l1_etmhf120 <= single_etmhf_i24;
    algo(5) <= l1_etmhf120;
-- 20 L1_UnpairedBunchBptxPlus : EXT_BPTX_B1NotB2_VME
    l1_unpaired_bunch_bptx_plus <= single_ext_i25;
    algo(3) <= l1_unpaired_bunch_bptx_plus;
-- 21 L1_UnpairedBunchBptxMinus : EXT_BPTX_B2NotB1_VME
    l1_unpaired_bunch_bptx_minus <= single_ext_i26;
    algo(2) <= l1_unpaired_bunch_bptx_minus;
-- 22 L1_DoubleJet_100_30_DoubleJet30_Mass_Min620 : comb{JET100,JET30} AND mass_inv{JET30,JET30}[MASS_MIN_620]
    l1_double_jet_100_30_double_jet30_mass_min620 <= double_jet_i27 and invariant_mass_i28;
    algo(19) <= l1_double_jet_100_30_double_jet30_mass_min620;
-- 23 L1_DoubleJet_110_35_DoubleJet35_Mass_Min620 : comb{JET110,JET35} AND mass_inv{JET35,JET35}[MASS_MIN_620]
    l1_double_jet_110_35_double_jet35_mass_min620 <= double_jet_i29 and invariant_mass_i30;
    algo(20) <= l1_double_jet_110_35_double_jet35_mass_min620;
-- 24 L1_MinimumBiasHF0_AND_BptxAND : MBT0HFP1 AND MBT0HFM1
    l1_minimum_bias_hf0_and_bptx_and <= single_mbt0_hfp_i31 and single_mbt0_hfm_i32;
    algo(9) <= l1_minimum_bias_hf0_and_bptx_and;
-- 25 L1_ETTAsym40 : ASYMET40
    l1_ett_asym40 <= single_asymet_i33;
    algo(6) <= l1_ett_asym40;
-- 26 L1_ETTAsym50 : ASYMET50
    l1_ett_asym50 <= single_asymet_i34;
    algo(7) <= l1_ett_asym50;
-- 27 L1_Centrality_50_100 : (CENT0 OR CENT1 OR CENT2)
    l1_centrality_50_100 <= ( single_cent0_i35 or single_cent1_i36 or single_cent2_i37 );
    algo(0) <= l1_centrality_50_100;
-- 28 L1_Centrality_Saturation : CENT7
    l1_centrality_saturation <= single_cent7_i38;
    algo(1) <= l1_centrality_saturation;

end architecture rtl;
